### ISSUE TITLE
BOOKMARKLET.md does not load ramda 

### ISSUE THREAD

**Issue by Walms** [ramda/ramda#3193] opened 2021-10-19 00:31 UTC
In the docs the bookmarklet is referred to as a way to insert ramda into any page. Yet there is no code there?

**Comment by customcommander** [comment] 2021-12-17 08:58
Just in the spirit of managing issues I'm tempted to close this one as a duplicate of #3128. Any objection?

**Closed** 2021-12-17 21:51 UTC
