### ISSUE TITLE
Support of Map

### ISSUE THREAD

**Issue by eduardofcgo** [ramda/ramda#3023] opened 2020-05-08 00:10 UTC
Should functions like `invertObj` or `invert` for example support `Map` as well, and not only objects?

**Comment by CrossEye** [comment] 2020-05-08 22:22
Yes, if we ever get `1.0` out the door, later versions will support more modern JS constructs.  That will definitely include Map for some functions.

**Comment by customcommander** [comment] 2021-12-27 15:36
Closing as duplicate of #1055

**Closed by customcommander** 2021-12-27 15:36 UTC
Labels: duplicate, 1.0 discussion
