### ISSUE TITLE
Mention "constant" in the docs

### ISSUE THREAD

**Issue by bergus** [ramda/ramda#1038] opened 2015-04-21 12:54 UTC
I was searching for a function in the http://ramdajs.com/docs/ that created a *constant* function, i.e constantly returns the given value regardless of its input. In Haskell, `const` does this.

Only by conincidence I noticed that such function already exists, only going by the name `R.always`. Can we add a synonym, rename, or at least mention the term "constant" in the docs so that it can be found via `Ctrl`+`F`?

**Comment by TheLudd** [comment] 2015-04-21 13:10
Just a note here. It has been discussed on gitter that `always` is not *truly* a constant function depending on how it is viewed. Example:

```
var arr = [0];
var alwaysArrayWithZero = R.always(arr);
arr[0] = 1;
alwaysArrayWithZero() // => [1]
```

It could be argued that a `constant` function should guard against this.

**Comment by buzzdecafe** [comment] 2015-04-21 13:43
sounds like another issue @TheLudd !

in the meantime, we should certainly add an `@aka` or some such to the docs as suggested here: #792

**Comment by CrossEye** [comment] 2015-04-21 13:49
@bergus: We've moved entirely away from aliases for reasons described best by [this parable][pa].

We really would like to find a good way to add a list of AKAs from other libraries and other languages to the docs.  `constant` and `const` would be good such tags for this one.


@TheLudd: I don't find that too worrying, I guess.  We could, I suppose, do a deep clone of the object passed to `always`, once received and before returning, but that might break other people's expectations.  I think that reference identity here is probably enough.  Of course, I've mostly used it for primitive values, so it doesn't affect me either way.  Has the current behavior caused problems for you?



  [pa]: https://github.com/ramda/ramda/pull/574#issuecomment-64124850

**Comment by TheLudd** [comment] 2015-04-21 14:19
@CrossEye No It hasn't. I think mainly because I don't mutate data since I use ramda to modify objects and arrays. I have no issue with `always` remaining the way it is. I am just not sure if I consider it quite the same thing as `constant`.

**Comment by buzzdecafe** [comment] 2015-04-21 14:32
for the purposes of searching the docs, i'd say they are close enough

**Comment by sebinsua** [comment] 2015-05-14 16:23
Agreed that it would be nice if methods were tagged with other terms that people might search for when looking for them.

The aim being not that the method is aliased itself, but that it is easier to find without knowing its name.

**Comment by davidchambers** [comment] 2015-05-14 17:06
We needn't do anything fancy here. We could just update the description to contain the word "constant". :)

**Comment by buzzdecafe** [comment] 2015-05-14 17:08
that's certainly easier than a custom tag :+1:

**Comment by CrossEye** [comment] 2015-05-14 18:52
It is _easier_, but is it in the end _simpler_?  I don't mean to be a smartass here, but it's an interesting question.  If we do these _ad hoc_, just by making sure we include the aka's somewhere in the description, someone would be able to find them with CTRL-F, true.  But if we added a JSDoc tag, we could later decide to add sophistication to our search widget so that someone searching for `foldl` was shown `reduce`, and they would _still_ be able to find them with CTRL-F.

**Comment by buzzdecafe** [comment] 2015-05-14 19:21
thanks for volunteering, @CrossEye !

**Comment by buzzdecafe** [comment] 2015-05-19 22:00
duplicate of #792

**Comment by alexanderkjeldaas** [comment] 2015-06-22 07:09
The search box on the ramda website does not respond to 'const', so the "AKA" in the documentation needs to be surfaced better IMO.

**Comment by CrossEye** [comment] 2015-06-22 11:37
I actually was working on this yesterday, but having issues with JSDoc.  I hope to have those figured out soon.

**Closed** 2015-07-12 21:35 UTC
Labels: documentation

**Comment by CrossEye** [comment] 2015-07-13 11:35
I never did get back to the JSDoc issues I was working on.  Someday soon.

**Comment by jkarttunen** [comment] 2019-04-22 13:33
Yeah, would be nice, this is a bit cryptic: https://ramdajs.com/docs/#cond
