### ISSUE TITLE
"Try Ramda" is broken

### ISSUE THREAD

**Issue by Lambda89** [ramda/ramda#1925] opened 2016-09-30 06:56 UTC
The live editor fails due to server problems

http://ramdajs.com/repl/?v=0.22.1

Don't know if this is really Github-worthy, but I found no contact information on the site.

Best regards

**Comment by buzzdecafe** [comment] 2016-09-30 10:22
yup, already aware of that thanks. duplicate of #1873

**Closed by buzzdecafe** 2016-09-30 10:22 UTC
