### ISSUE TITLE
R.inc “works” when applied to singleton array

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#1787] opened 2016-05-31 05:47 UTC
This is rather surprising:

``` javascript
> R.inc([1, 2, 3])
NaN

> R.inc([1, 2])
NaN

> R.inc([1])
2

> R.inc([null])
1
```

Is this simply a case of garbage in, garbage out?

Let's document our stance on type errors. Many Ramda issues are concerned with what constitutes a type error and how type errors are handled. It would be great to have some clarity.

Do you appreciate the fact that `R.inc([null])` evaluates to `1`, @CrossEye, because it allows for composition, or would you prefer to throw in this case?

**Comment by ascartabelli** [comment] 2016-05-31 06:17
@davidchambers not really surprising, actually, but it can be annoying: it's because you used the `Number` constructor as a function to convert the type to number. The same happens if you use, say, `+` or `-` as unary operators.
Without the conversion the result of `R.inc([1])` would have been the string "11" though.

You can follow the rationale in the ECMA specifications, starting from the [`Number` constructor](http://www.ecma-international.org/ecma-262/6.0/#sec-number-constructor-number-value), then going to the [conversion to number](http://www.ecma-international.org/ecma-262/6.0/#sec-tonumber) to finally land at the ["ToPrimitive"](http://www.ecma-international.org/ecma-262/6.0/#sec-toprimitive) operation which is the one causing it.

Even when you know it it's easy to forget about it and fall into a pit of unexpected behaviours...

**Comment by davidchambers** [comment] 2016-05-31 06:30
#1573 and #1580 are related to this issue.

**Comment by buzzdecafe** [comment] 2016-05-31 10:42
ugh javascript. should throw IMO

**Comment by Bradcomp** [comment] 2016-05-31 15:55
If `inc` throws, should `add`, `subtract`, etc. throw as well?

**Comment by buzzdecafe** [comment] 2016-05-31 17:42
imo we should release 1.0 soon and add stronger type enforcement to the list of things to consider for 2.0

**Comment by CrossEye** [comment] 2016-06-01 04:03
> Do you appreciate the fact that `R.inc([null])` evaluates to `1`, @CrossEye, because it allows for composition, or would you prefer to throw in this case?

I would probably be happiest if it returned `NaN`, but failing that, I'm glad that it returns a Number rather than throwing.  I can't imagine coding all the odd cases for all our functions to deal with such possibilities.  So garbage in, garbage out.

**Comment by davidchambers** [comment] 2016-06-02 00:06
> I'm glad that it returns a Number rather than throwing.

Imagine a complex `estimateCreditRisk` function intended to return a number between 0 (no risk) and 1 (extremely high risk). If somewhere deep in the function's innards there's a bug which results in applying `R.inc` to `[null]` rather than a number, what is the relative desirability of each of the following?

```javascript
estimateCreditRisk(alice);
// => 0.9761904761904762
```

```javascript
estimateCreditRisk(alice);
// => NaN
```

```javascript
estimateCreditRisk(alice);
// ! TypeError: Cannot increment [null]
```

In my view the last of these is the most desirable, as it makes it clear that something is amiss and tells us what is amiss (via a stack trace).

Returning `NaN` makes it clear that something is amiss, though provides no indication of *what*.

Returning `0.9761904761904762` is disastrous: we've classified Alice's credit risk as extremely high! This is not a case of garbage in, garbage out, as the return value is within the expected range. It's not obvious that anything is amiss. Who knows how many loan applications will be erroneously rejected before the bug is discovered?

I consider `R.inc([null])` evaluating to `1` unacceptable.

**Comment by buzzdecafe** [comment] 2016-06-02 01:36
> I consider `R.inc([null])` evaluating to 1 unacceptable.

i am inclined to agree, this is very undesirable behavior. more and more i think we want to move toward stronger typing, but i don't want to be half-arsed, i want a consistent plan for it

**Comment by CrossEye** [comment] 2016-06-02 02:48
> I consider `R.inc([null])` evaluating to `1` unacceptable.

I would certainly go along with 'undesirable'.  I would like to see a fix for this.  I would have to see a cure to know if it seems worse than the disease.  But I do think this is still a case of garbage in, garbage out.  The fact that the garbage that come out looks similar to possible good output is unfortunate, but if you don't like that, then don't supply bad input.

While your story presents a good case for throwing, there are other stories.

Imagine a complex `reportTotalOrders` function intended to return a positive integer representing all the web orders the user has made through my site, including the current order. If somewhere deep in the function's innards there's a bug which results in applying `R.inc` to `[null]` rather than a number, what is the relative desirability of each of the following?

```javascript
reportTotalOrders(currentUser);
// => 0.9761904761904762
```

```javascript
reportTotalOrders(currentUser);
// => NaN
```

```javascript
reportTotalOrders(currentUser);
// ! TypeError: Cannot increment [null]
```

Oh yes, a little more context: This function is part of a large `compose`d function used to display the summary page of an ecomm site, so that the user about to enter her credit card can note how many purchases she's made here before.

Returning `NaN` or `0.9761904761904762` will expose us to a bit of ridicule: "Those idiots don't even know how to add whole numbers?!"  But throwing an exception will break the chain, stop the display of the page, and most likely lose us the sale.  But as sales are abandoned every day, this might well get lost in the shuffle.  Who knows how many sales will be accidentally abandoned before the bug is discovered?

Yes, we could add `try-catch`, but that means starting to replace our simple functional pipelines with imperative blocks, all because of an error that should not ever happen and is only of minor consequence when it does.  That's an awful big dog to be wagged by such a tiny tail.

-----

I have an important question.  Did you notice that `inc([null]); //=> 1` by inspection of the function, by some sort of property-based testing, or by a real-world run-in with data that you never expected to get being passed to `inc`?  The last one would scare me the most, but it seems quite unlikely to me.

While "quite unlikely" is not the best way to protect against the idiocies of the world, I am not in favor of trying to guard against every possible mistake or malfeasance of users.  I suppose I should really create a pristine environment and grab the `Date` constructor from there if I ever need a date object, because someone could have overridden the one on the global object.  But I don't bother, and am unlikely to lose sleep over this.  That's how I feel about a lot of run-time type-checking.

I see that you are (or OCaml is) slowly winning over @buzzdecafe.  I'm not there yet, not even close.  I see all the advantages of stronger type checking, and I like languages (and even libraries) that support it, I still don't feel that Ramda should be even slightly trying to turn JS into ML.

Ok, this has been a lot to type on my little tablet.  Someday I'm going to learn @buzzdecafe's secret of pithiness!

**Comment by ascartabelli** [comment] 2016-06-02 04:05
If you don't mind me barging in my suggestion would be, as I mentioned elsewhere, to think in terms of problem domain. In this case one good question would be "what we want Ramda to be?". Utility library? Programming environment? Something else?

If I'm looking at Ramda now as a user I would say it's a utility library and I would be with @CrossEye saying "let it slide".

If you decide to take a more aggressive stance on the matter this should be a library-wide action though.
This also adds the question "what's the performance cost of my action?" to the game.

Consider that, talking about numbers alone, we have plenty of cases that evaluate to a number, not `NaN`, using the `Number` constructor or equivalent operation.
On top of my mind:
- strings containing only numbers or a number representation (e.g.`"0xff"`, `"2e05"`)
- dates
- booleans
- arrays of one element, with the one element being a number or one string like in the above example

One can replace the `Number` conversion with some _ad-hoc_ function, or even add some function decorators to help intercept and treat parameters, but first of all I would try to answer the question "what we want Ramda to be?".

**Comment by ascartabelli** [comment] 2016-06-02 07:02
Now that I have had some coffee flowing, I have the doubt that my comment wasn't properly clear about what I meant by "thinking in terms of problem domain".
@davidchambers' example is a valid use case, but it should also be a clear indicator that the question I posed earlier should be answered first.
Let's stick to the specific case and consider for example:
```javascript
R.inc(-.8) // => 0.19999999999999996

let n = 9007199254740992;
R.inc(n) === n // => true
R.inc(R.inc(n)) // => true
```
So, are these in your problem domain or not?

I don't know how you see Ramda, but if I think of it as a library to make functional programming easier I would even take a step back.
I would implement `R.add` and `R.inc` as simple wrappers over native operators:
```javascript
const add = a => b => a + b;
const inc = n => ++n; // should behave exactly like your current `inc`
```
That or not implement them at all.
This is only a simple case, but when we try to do "too much" we invade others' problem domain, in @davidchambers' example the guy writing the `estimateCreditRisk` app, and sometimes we even make things more difficult for them.

**Comment by buzzdecafe** [comment] 2016-06-04 00:25
thanks for your input @ascartabelli . no need to apologize for "barging in". 

On the contrary, i think you have put your finger on exactly what is at stake here. Who is this library for? What does it deliver? Is it an unopinionated toolkit for JavaScript developers? or should it prescribe a certain way of writing code? 

For me, these lines are moving all the time. I have historically objected to run-time type-checking -- Let if fail! No hand-holding! But my perspective is changing. ramda occupies a very weird space. the auto-currying, compositional focus drives it in the direction of ML-ish languages. Among the primary features of those languages are static typing, type inference, and pattern matching. ramda has none of these. you could argue ramda does some fantasy-land-style "typing"; but it is very, **very** weak compared to the real thing (and certainly not static). pattern matching is probably beyond our reach due to the limitations of the host language. 

we cannot get the static stuff in JS. Well, without a build step. But if you are going to have a build step, then _why use JavaScript?_ 

Run-time type checking is a very poor imitation of the real thing. And since the environment this lib will be running in is about as Wild West as it gets, I am deeply skeptical that run-time type-checking can deliver what it promises. @davidchambers and i have an ongoing discussion running on this topic. Surprisingly, I am coming around to his POV! At least part way. The skepticism remains. But maybe _something_ is better than _nothing_. Perhaps I should not be willing to sacrifice "good enough" on the altar of perfection.

Also note that ramda started as a personal learning project. Now many more people than i ever expected have found it useful. That has been an amazing ride ... but it was never the goal, and never will be. i have no interest in being a library maintainer. but i remain very motivated to learn new stuff, wherever that leads.

**Comment by davidchambers** [comment] 2016-06-04 00:56
> Did you notice that `inc([null]); //=> 1` by inspection of the function, by some sort of property-based testing, or by a real-world run-in with data that you never expected to get being passed to `inc`?

I don't recall. I may have written `R.inc([1])` when I meant to write `R.map(R.inc, [1])`. You once implied, @CrossEye, that you don't unwittingly introduce type errors when writing code. I certainly do. :stuck_out_tongue_winking_eye:

> Run-time type checking is a very poor imitation of the real thing.

What is “the real thing”? Setting aside dependently typed languages (because I don't know enough about them to comment), static type checking is not strictly superior to dynamic type checking. In Racket, for example, one could write a contract for `nth` to ensure that the integer provided is a valid list index. This may be possible in Haskell (apparently anything is possible if there's no limit to the number of language extensions one is willing to enable), yet the Prelude's `(!!)` has type `[a] -> Int -> a` and raises a run-time exception if the index is out of bounds. Static type checking informs us of our errors before we've even run the code; dynamic type checking allows us to express more constraints in the type system.

**Comment by CrossEye** [comment] 2016-06-04 01:33
@davidchambers 
> You once implied, @CrossEye, that you don't unwittingly introduce type errors when writing code. I certainly do. :stuck_out_tongue_winking_eye:

If I said anything like that, it was certainly an exaggeration.  But it is way down the list of problems I run into coding.

>> Run-time type checking is a very poor imitation of the real thing.

> What is “the real thing”? Setting aside dependently typed languages (because I don't know enough about them to comment), static type checking is not strictly superior to dynamic type checking

That's a fair point, but I think my comparison should also be fairly obvious.  The static typing in Haskell is very powerful, and very useful, and leads to a very different design-build-test cycle than I practice in a dynamically typed language.

I like what you're doing with Sanctuary, including sanctuary-def.  I think it's a very useful, powerful approach.  But I used it more when it seemed mostly focused on safer versions of things like `head` and `find` than I do now.

I've played with many ML-based and many LISP-based languages.  And while I like both, I still prefer working with the LISP-y ones.  And as JS seems closer to those ones, efforts to move it too far towards the ML ones feels like a round peg in a square hole.

**Comment by ascartabelli** [comment] 2016-06-07 06:01
@buzzdecafe: 
> thanks for your input @ascartabelli . no need to apologize for "barging in".
> On the contrary, i think you have put your finger on exactly what is at stake here.

Well, it seemed more of a discussion for Ramda's staff at that point, so I felt like I was barging in.
Glad that my input was appreciated though.

> i have no interest in being a library maintainer

Don't worry: Ramda already raised enough attention from the community that you shouldn't run the risk of becoming one.
In a short time you'll probably be able to relax and become only a supervisor, if you prefer!

**Closed** 2017-10-18 18:36 UTC
