### ISSUE TITLE
Add an expose function to make use of Ramda comfortable

### ISSUE THREAD

**Issue by honzabrecka** [ramda/ramda#1166] opened 2015-06-08 08:54 UTC
Hi, I spent a while with ClojureScript and then came back to Ramda and I have, most probably, an silly idea. Ramda is a "core language", which means that write before every single function `R.` (or `ramda.` or whatever your import name is) prefix is pretty uncomfortable. Readability of code is bad, it's lot of "redundant" writing, ... So the idea is to provide an `expose` function:

```js
ramda.exposeTo = function(target) {
  for (var f in ramda) target[f] = ramda[f];
};

// use
require('ramda').exposeTo(global);
map(f, filter(g, [1, 2, 3]));
```

What do you think?

**Comment by paldepind** [comment] 2015-06-08 09:57
First of all you should check if the property is already in the target and throw or log an error if it is. Otherwise unexpected things can happend when exposing to the root scope.

Regarding the proposal. I'm not sure. I know that a bunch of people like doing that and I can see the appeal. But doing so is slightly sketchy. If a user does it himself he is responsible for any negative consequences. But if Ramda includes such a function we promote the behaviour and overtake responsibility.

It could be documented with a warning. But exposing more than 200 functions to the root scope is still kinda crazy.

**Comment by CrossEye** [comment] 2015-06-08 11:31
We actually removed such a function not terribly long ago. 

I think I was one of the few who actually wanted to keep it, as I like working in that manner, but I really couldn't argue against removing the only function that modified is input data. 

Perhaps this should go in the [Cookbook][co].


  [co]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by paldepind** [comment] 2015-06-08 12:13
> Perhaps this should go in the Cookbook.

:+1:

**Comment by CrossEye** [comment] 2015-06-08 13:54
@honzabrecka: Would you be willing to add an entry to  the [Cookbook][co] Wiki page?


  [co]: https://github.com/ramda/ramda/wiki/Cookbook

**Comment by honzabrecka** [comment] 2015-06-08 14:34
```js
var R = require('ramda);
R.mixin(global, R);
```

Is this `installTo` sufficient?

**Comment by paldepind** [comment] 2015-06-08 14:35
> Is this installTo sufficient?

You should check if the property is already in the target and throw or log an error if it is.

**Comment by buzzdecafe** [comment] 2015-06-08 14:40
> Is this installTo sufficient?

there is no `R.mixin`, especially not one that mutates its first argument.

**Comment by raine** [comment] 2015-06-08 21:18
I've experienced a very obscure bug as a result of extending global with Ramda, wouldn't recommend doing it except in REPL and small scripts.

**Comment by CrossEye** [comment] 2015-06-08 22:55
@raine: Can you describe what happened?  I'd be curious.  I know that there are two or three functions with names that conflict with something on the native or browser host systems.  But that's all I know about.

**Comment by raine** [comment] 2015-06-09 09:26
I had an issue where [`through2`](https://www.npmjs.com/package/through2) would not emit further any one of the chunks it received.

I didn't look into back then, but now at a closer inspection it seems `isNaN` is the reason. `through2` has dependency that uses global `isNaN` and expects different behavior for `undefined`.

```js
var R = require('ramda');
var stream = require('stream');
var through2 = require('through2');

global.isNaN = R.isNaN;

var s = new stream.PassThrough();
s.write('foo');

s.pipe(through2(function(chunk, enc, next) {
  this.push(chunk);
  next();
})).pipe(process.stdout);
```

```
node_modules/readable-stream/lib/_stream_readable.js
244:  if (n === null || isNaN(n)) {
```

---

```
global.isNaN = R.isNaN
```

```
isNaN(0) => false
isNaN(undefined) => false
```

```
// global.isNaN = R.isNaN
```

```
isNaN(0) => false
isNaN(undefined) => true
isNaN(undefined) => true
```

**Comment by CrossEye** [comment] 2015-06-09 13:04
Well, that one at least should be going away, as our `isNaN` should be removed in the next release.  But we still overlap in the browser with `find`, and `toString`.

The reason for the discrepancy was the realization that `isNaN` had some pretty awful behavior, and  there was added to `Number` [another version][na] of it, with slightly better behavior.  Our version was modeled off this one.

  [na]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Comment by burabure** [comment] 2015-06-10 02:30
with es6 modules you could just import what you need
```js
import map from 'ramda'
```

**Comment by CrossEye** [comment] 2015-06-10 16:07
The problem is that for even slightly complicated code, this can become unwieldy.  In our [build script][bs], we would have to do this:

```js
import { __, curry, pipe, always, partialRight, ifElse, partial, concat, memoize, allPass, 
        pathEq, tap, chain, prop, of, reject, either, map, forEach, cond, complement, pluck, 
        converge, eqDeep, identity, sortBy, identity, path, concat, last, replace, nthArg, 
        toUpper, takeWhile, both, all, contains, head, tail, append, sortBy, keys, join } 
    from 'ramda'
```

Or maybe if we were organized and didn't add them haphazardly, this:

```js
import { __, all, allPass, always, append, both, chain, complement, concat, concat, cond, 
        contains, converge, curry, either, eqDeep, forEach, head, identity, identity, ifElse, 
        join, keys, last, map, memoize, nthArg, of, partial, partialRight, path, pathEq, 
        pipe, pluck, prop, reject, replace, sortBy, sortBy, tail, takeWhile, tap, toUpper }
    from 'ramda'
```

Granted, this was written by people who really understand Ramda.  But at fewer then 300 lines, it's not some monstrous file, either.

  [bs]: https://github.com/ramda/ramda/blob/3b3e9e8fd866faae9b107a93de305a547f94f038/scripts/build

**Comment by jethrolarson** [comment] 2015-06-12 19:20
with(require('ramda')){
  R.lolololol
}

**Comment by asaf-romano** [comment] 2015-06-24 17:15
In practice, you don't have much of a choice in a node environment. There is = no way (afaik) to reference the module-local "global" (|this| is undefined), and installing ramda into *the* global object (there's only one global for all modules) is a very bad idea - likely to break third-party modules and such - so, all in all, there's nothing to install ramda functions into.

What @CrossEye demonstrated is pretty much what I regularly do these days. It's not pretty but I prefer 4-5 ugly lines at the top of each module than prefixing everything with |R.|

**Comment by raine** [comment] 2015-09-28 08:25
I wrote a tool yesterday to help manage required Ramda functions when using destructuring assignment.

https://github.com/raine/ramda-destruct

**Comment by buzzdecafe** [comment] 2015-11-18 20:51
closing w/o prejudice

**Closed by buzzdecafe** 2015-11-18 20:51 UTC
Labels: cookbook

**Comment by coderofsalvation** [comment] 2016-01-01 23:09
Forgive me for commenting on a closing issue, but since this issue comes up fairly easy using google, here's how I just cherrypicked 'prop' in coffeescript:

    prop = require 'ramda/src/prop'
    data = [{ id: 'foo' }, { id: 'bar' }]                                           
    console.dir data.map prop 'id'

Which leads me to the question: are all ramda functions standalone?
Because the approach above could work nice for tools like browserify.

**Comment by jethrolarson** [comment] 2016-01-03 21:32
They're not standalone. Many make calls to other functions. However the
source is broken up into many small files that are included via node
require so using browserify is pretty easy
