### ISSUE TITLE
Switch to the correct implementation of the `curry` function.

### ISSUE THREAD

**Issue by aaditmshah** [ramda/ramda#732] opened 2015-01-17 06:09 UTC
I recently wrote a question and an answer on StackOverflow illustrating how the current implementations of the `curry` function are wrong:

[How to correctly curry a function in JavaScript?](http://stackoverflow.com/q/27996544/783743)

Please switch to the correct implementation of the `curry` function.

**Comment by davidchambers** [comment] 2015-01-17 09:35
This seems great. Would you like to submit a pull request?

@buzzdecafe and @CrossEye likely chose the current behaviour for a reason. I wasn't on the scene back then, so I don't know the rationale.

**Comment by buzzdecafe** [comment] 2015-01-17 13:43
if we can get `project = compose(map, pick)` out of this, then I am all for it. One point where I disagree is what happens when you call a curried function with no arguments. IMO that's an error and should be handled as such.

**Comment by aaditmshah** [comment] 2015-01-17 14:14
@buzzdecafe There are three things you can do when a curried function is called with no arguments:

1. Return the curried function itself.
2. Throw a &ldquo;no arguments&rdquo; error.
3. Do nothing at all.

The first two cases are pessimistic. You are assuming that your end users might be stupid enough to call a curried function with no arguments:

1. In the first case you allow the end user to call the curried function with no arguments, but you return the curried function itself thereby circumventing the creation of a new curried function.
2. In the second you don't allow the end user to call the curried function with no arguments.

In both cases you have an initial check for no arguments. This check is not part of the core logic of the `curry` function itself, and every time an end user calls the curried function this check will occur. For a correct program (one which never calls a curried function with no arguments) it means that this check will always be `false`. Hence, it's just a waste of CPU cycles.

On the other hand, the third case is optimistic. It assumes that your end users aren't stupid enough to call a curried function with no arguments. Hence it doesn't penalize them with unnecessary &ldquo;no arguments&rdquo; checks. For a correct program (one which never calls a curried function with no arguments) this means that we can skip the useless check, resulting in faster code.

For an incorrect program (one which does call a curried function with no arguments) this means that the `curry` function will unnecessarily create a new curried function every time a curried function is called with no arguments. However, the program will still execute correctly, only slower. In my opinion, this is a reasonable tradeoff.

My mantra is &ldquo;if somebody is stupid enough to call a curried function with no arguments, then they deserve the performance hit. Others shouldn't needlessly be punished just because of a few stupid people.&rdquo;

In the end however, it all depends upon what you think about your end users. Do you think that they are smart or do you think that they are stupid? Do you think that it's your duty to warn them when they do something stupid or do you think they should be forgiven.

P.S. I am creating a pull request.

**Comment by aaditmshah** [comment] 2015-01-17 14:14
Sorry, clicked &ldquo;Close and comment&rdquo; instead of just &ldquo;Comment&rdquo; by mistake.

**Comment by buzzdecafe** [comment] 2015-01-17 14:34
@aaditmshah a thoughtful response as usual. 

> In the end however, it all depends upon what you think about your end users. Do you think that they are smart or do you think that they are stupid? Do you think that it's your duty to warn them when they do something stupid or do you think that they should be forgiven?

In most cases we have taken the "let it fail" approach, i.e. give the user the benefit of the doubt that they are doing the right thing, and don't hold their hand and *enforce* correct behavior. What I am afraid of in this case is that the user may *inadvertently* get themselves into a situation where something in the chain fails, and the next function is somehow invoked with no args. It's possible the program could continue executing as if nothing was amiss until eventually it blows up. That could be a very subtle bug to ferret out. So that's why I took the position that we should throw when a curried function is invoked with no arguments.

But maybe I should trust users to do the right thing, as I do virtually everywhere else. I know @CrossEye never was comfortable with the decision to throw on no arguments. I don't think I would defend that position too vigorously. 

I am looking forward to your PR--it's not too often we get a chance to potentially upgrade behavior on something so fundamental.

**Comment by aaditmshah** [comment] 2015-01-17 15:43
Is it important for a curried function to have the correct `length` property?

**Comment by buzzdecafe** [comment] 2015-01-17 16:39
yes, we've made an effort to preserve the arity of curried functions

**Comment by aaditmshah** [comment] 2015-01-17 19:06
Unfortunately it's not possible to know the arities of all the functions beforehand because of the way extra arguments are handled. For example, consider:

```javascript
var countWhere = compose(compose(length), filter);
```

We as programmers know that `countWhere` is a function of arity 2. However, at runtime all we know is that `countWhere` is a function of arity 1 (because `compose` is a function of arity 3 out of which 2 arguments are already fixed). There's no way to determine at runtime (without making the definition of `countWhere` more complex) that `countWhere` is a function of arity 2 (because of 1 extra argument).

Currently I can't think of any good way to preserve the arity of curried functions when there are extra arguments involved; and to be candid, I am lazy. I don't see any reason to preserve the arity of curried functions anyway. Hence, I am going to convince you to give up on the preservation of the arity of curried functions by making a few arguments:

1. Preserving the arity of curried functions comes at a cost, and that cost is performance. All the curried functions created by `curryN` have a two level indirection. For example, say I have a function `foo` and I curry it: `var bar = curryN(foo, 3);`. Now `bar` is a wrapper function of arity 3. When I call it, it simply passes its arguments to another function, which does all the work. By creating a wrapper function of a given arity you've introduced one level of indirection. However, currying a function is itself an indirection. Hence all curried functions have not one, but two levels of indirection (one for currying and one for preserving arity). This makes calling curried functions needlessly slow.
2. By trying to preserve the arity of curried functions you make your code needlessly more complex. In my humble opinion, adding complexity to a program is only justifiable if it solves some essential problem. For example, [when multiplying two matrices if you transpose the second matrix before multiplying them](http://stackoverflow.com/q/12701648/783743) (to increase the locality of reference of the matrix, thereby reducing the cache miss rate) then this is justifiable complexity added to the program. However, adding complexity to the program just to preserve the arity of functions doesn't seem justifiable to me.

In short, I don't see any good use for preserving the arity of curried functions. To me it seems like you're telling me _&ldquo;Hey, your curried functions will run twice as slow they should because of two levels of indirection instead of one, but at least they will have the correct `length`. That's a good thing right? You know... in case you didn't already know the `length` of the function that you wrote, then you can query for it at runtime. Or **if** you have code which depends upon the correct `length` of a function (which you really shouldn't because not only is it bad design but also because it is inaccurate, with variadic arguments and all) then at least that code will work correctly.&rdquo;_

Sorry for the rant. It's just that I can't see any way of preserving the length of curried function when there are extra arguments involved, and neither am I interested in doing so. If it's cool with you may I not preserve the length of curried functions? Doing so allows me to differentiate between curried functions and non-curried functions (because no self-respecting functional programmer would ever write a function with no arguments). This allows me to test whether or not to curry a function. If the function is already curried then there's no need to curry it again:

```javascript
function curry(f) {
    var length = f.length;
    if (length > 0) return partial(f, length, []);
    else return f;  // f is already curried
}
```

**Comment by kedashoe** [comment] 2015-01-17 19:17
This seems pretty awesome, but I must admit my first inclination is to agree with

http://stackoverflow.com/questions/20279306/what-does-f-g-mean-in-haskell#comment30265157_20279307

that this seems more obtuse to me. I'm not sure why I would want to write something like

`var countWhere = compose(compose(length), filter);`

when it can already be achieved in what to me are more readable ways. On the other hand, I'm not sure I understand the examples. In your article you say repeatedly

' the correct result [1,3,5]

or something to that effect, but I looks to me like the correct result should simply the integer `3`? Aren't we creating a composition that in the end calls your length function, and the length of [1, 3, 5] is 3?

In any event, great posts! Will be interested to see where ramda goes with this :)

**Comment by aaditmshah** [comment] 2015-01-17 19:35
Yes, it was indeed a mistake on my part. The correct result is indeed `3` and not `[1,3,5]`. I corrected it.

Pointfree programming is a bit of a stretch, and I agree that it's not nice to work with no arguments. However, you don't need to. You can define a `compose2` function which will allow you to compose `length` and `filter` as follows (just like you would do in functional languages like Haskell):

```javascript
var compose2 = compose(compose, compose);

// or

var compose2 = curry(function (f, g, x, y) {
    return f(g(x, y));
});

// usage

var countWhere = compose2(length, filter);
```

I would like to see a lot of the cruft like `useWith` removed from Ramda.

**Comment by buzzdecafe** [comment] 2015-01-17 19:48
see : https://github.com/ramda/ramda/pull/140#issuecomment-48129363 

Arity is all-or-nothing: either we're going to expect arity to be correct, or we're not, and *caveat emptor*.
So I don't know that we can remove arity from `curry` without making sure we aren't relying on arity anywhere else. 

I expect @CrossEye will want a word or twon on the subject as well...

**Comment by davidchambers** [comment] 2015-01-17 20:07
> If it's cool with you may I not preserve the length of curried functions? Doing so allows me to differentiate between curried functions and non-curried functions (because no self-respecting functional programmer would ever write a function with no arguments). This allows me to test whether or not to curry a function. If the function is already curried then there's no need to curry it again:
>
> ```javascript
> function curry(f) {
>     var length = f.length;
>     if (length > 0) return partial(f, length, []);
>     else return f;  // f is already curried
> }
> ```

It's interesting that you argue that a function's length property can be misleading, yet rely on it being accurate in `curry`.

`R.always(42)` returns a function with length 0. Perhaps you would argue it should have length 1?

**Comment by aaditmshah** [comment] 2015-01-17 20:38
Technically, yes. The `always` function is the equivalent to the `const` function in Haskell which has the type `a -> b -> a`. Types tell a lot about the function. So, yes. I would argue that `always` should return a function with length 1, even if it doesn't use it.

I see that `always` is function is implemented as follows:

```javascript
var always = R.always = function always(val) {
    return function() {
        return val;
    };
};
```

Is there any particular reason that you're not implementing it as:

```javascript
var always = R.always = _curry2(function always(a, b) {
    return a;
});
```

Doing so justs seems more natural to me.

**Comment by davidchambers** [comment] 2015-01-17 20:46
I like your version of `always`. I'll submit a pull request.

**Comment by aaditmshah** [comment] 2015-01-17 20:53
The `length` of a function is misleading when the function is variadic, and I [strongly oppose variadic functions](http://stackoverflow.com/a/26701110/783743). I prefer Haskell over JavaScript because Haskell is simple and easy to reason about. I strongly believe in keeping things as simple as possible and hence I avoid variadic functions. In the absence of variadic functions the `length` of a function is always accurate (hence we simplified). In such a case the only reason you would write a function with no arguments is:

1. For a [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) of an object property.
2. For [laziness](http://stackoverflow.com/a/21441278/783743) ([reified thunks](http://stackoverflow.com/a/19862784/783743)).
3. For curried functions.

In all three cases, it doesn't make any sense to curry the functions. Getters don't need to be curried. Reified thunks don't need to be curried. Curried functions don't need to be curried. In fact, in the absence of variadic functions no nullary function needs to be curried at all, because in the absence of variadic functions a nullary function doesn't have any arguments at all. That's why I like to simplify. Simple code means that you can guarantee certain properties about your code.

**Comment by kedashoe** [comment] 2015-01-18 02:21
Off topic, but an honest question (not trying to be cheeky, I really am curious..) @aaditmshah, what aspects of Haskell do you not like?

**Comment by CrossEye** [comment] 2015-01-18 03:20
I'm still trying to grok all this.  I do have several concerns.  At the outset is the worry that this is simply trying to port Haskell notions into Javascript.  While we absolutely take inspiration from Haskell, from LISP, from ML, from Erlang, and from other functional languages, we are not trying to duplicate their features or to turn Javascript into a light version of any of them.

I'm a little worried that much of the argument hinges on a different notion of `compose` than we use.  To Ramda, `compose` is one of the very few variadic functions in the library, but it's fairly important to the style of coding that Ramda is meant to support than `compose` and its order-reversed twin `pipe` accept an indefinite number of functions.

As to the question of preserving arity, we've done that to remain good neighbors in the Javascript world.  We need the arity in order to curry a function.  If our output does not properly report arity, it cannot be used by other tools that also depend upon it (for other forms of partial application, or for whatever other reasons we might not even be able to imagine.)

So, with all that said, this article definitely points to a real problem.  Ideally in Ramda, we should be able to define `countWhere` like this:

    var countWhere = compose(length, filter);

And that works fine if we call it with both arguments:

    countWhere(odd, [1, 2, 3, 4, 5]); //=> 3

But it fails on this:

    // should be :: [Number] -> Number
    var countOdds = countWhere(odd); //=> 1, oops!
    // countOdds([1, 2, 3, 4, 5]) //=> FAIL

So there is a serious issue to address.

**Comment by aaditmshah** [comment] 2015-01-18 06:36
@kedashoe No language is perfect. There are quite a few things I don't like about Haskell:

1. Explicit `forall` [quantifiers escaping type synonyms](http://stackoverflow.com/q/27887907/783743).
2. Extensions like `TypeSynonymInstances` which can be [problematic](http://stackoverflow.com/a/26824138/783743).
3. Forcing infix type constructors to [start with a colon](http://stackoverflow.com/a/27000198/783743).
4. No extension for dependent typing (although we can [fake it](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=77D17FDB84710123FCC96C0BDF0AA7C4?doi=10.1.1.22.2636&rep=rep1&type=pdf)).
5. Applicative is [not a superclass of Monad yet](https://ro-che.info/ccc/21). It should really be exported by Prelude.

There's not much that I don't like about Haskell. There's a lot I don't like about JavaScript:

1. [Variadic functions](http://stackoverflow.com/a/26701110/783743).
2. [The constructor pattern](http://aaditmshah.github.io/why-prototypal-inheritance-matters/#toc_6).
3. [`new` as a keyword](http://aaditmshah.github.io/why-prototypal-inheritance-matters/#toc_1).
4. Incomplete type information. For example, given an array we know nothing about the type of elements in the array. Hence we have to implement type checks in the language ourselves.
5. Deep nested callbacks. We should have language level features for managing asynchronous programming. Something along the lines of the monadic `do` notation.
6. No tail call optimization.

**Comment by CrossEye** [comment] 2015-01-18 17:01
In my previous comment, I said that it was a problem that `compose(length, filter)` wasn't automatically curried.  But sleeping on this made me realize that I wasn't so sure.  It's easy enough to do if the functions to compose are not variadic, but when they are, we run into issues.  I looked at the logs and realized I'd argued the other side of this in #485.

I think we are still best off if we simply return a simple function here and let the user call `curry` on it if desired:

    var countWhere = curry(compose(length, filter));

@aaditmshah: You're presenting arguments that seem to be based on users working in the style you prefer (no variadic functions, for instance.)  How do you reconcile this with what is supposed to be a general-purpose library, opinionated to be sure, but not one meant to be prescriptive?  Should the library only support users supplying fixed-arity functions?

**Comment by ashnur** [comment] 2015-01-19 07:51
I just ran into this problem. I had a function defined as 
```
function a(x){ return function(y){ ... } }
```
and `R.flip` just failed on it. I was wondering why and I think it's because it assumes that all curried functions are "created" by `R.curry`

I could have opened a new issue for `R.flip` but I think this is mostly related on how ramda users approach currying, so I am asking it here: what do you think about this? I think that ramda functions shouldn't assume that curried functions are created by ramda - which means that they might not be able to take all their arguments at once.

**Comment by aaditmshah** [comment] 2015-01-19 08:53
@ashnur Try the following `flip` function. Does it work correctly now?

```javascript
var flip = curry(function (f, x, y) {
    return f(y, x);
});

function curry(f) {
    var length = f.length;
    if (length > 0) return partial(f, length, []);
    else return f;  // f is already curried
}

function partial(f, length, a) {
    return function () {
        var count = arguments.length;
        var arity = length;
        var part  = count < arity;
        var size  = part ? count : arity;
        var args  = new Array(size);
        var index = 0;

        while (index < size) args[index] = arguments[index++];
        if (part) return partial(f, arity - count, a.concat(args));
        var result = f.apply(null, a.concat(args));

        if (typeof result === "function")
            result = curry(result);

        if (arity < count) {
            var args = new Array(count - arity), number = 0;
            while (index < count) args[number++] = arguments[index++];
            return result.apply(null, args);
        }

        return result;
    };
}
```

**Comment by ashnur** [comment] 2015-01-19 09:34
@aaditmshah Yes, using that implementation allows me to write `a(1,2)` and returns/prints `2 1` 
even for functions declared like: 
``` 
function a(x){ return function(y){ console.log(x,y) } }
```

I think it's all because it recursively calls curry if a function returns another function even after it got all its arguments. Which I think the whole subject here :)

**Comment by CrossEye** [comment] 2015-01-19 14:36
> I was wondering why and I think it's because it assumes that all curried functions are "created" by `R.curry`.

Actually, it's because `flip` is based on a notion of a function being passed at least two arguments.  Ramda's `curry` is designed to make your functions work as expected whether called with all the arguments or with a smaller number of them.  But it can't turn this style function, which only expects one argument, into one that expects more.

In other words, your function is curried perhaps by the Haskell notion of currying.  But Ramda has a somewhat different notion:

    var f = R.curry(function(a, b, c) { /* ... */ });

These are now all equivalent:

    f(1, 2, 3);
    f(1, 2)(3);
    f(1)(2, 3);
    f(1)(2)(3);

But your function is callable only as `a(x)(y)`.  Our `flip` needs to be able to apply `a(x, y)` to the original function.

There is no question, though, that an example like this is making me think.

**Comment by ashnur** [comment] 2015-01-19 14:52
@CrossEye 
I wouldn't argue with you over this, you are obviously quite right in what you are saying about the function in my example. 

But this example comes from someone who decided to write all their functions as unary functions thus avoiding this whole mess about currying, which is what this issue is mostly about. 
When I realized what the problem is, I could easily rewrite those functions using `R.curry`.

However the question still remains: I am trying to work with a number of other libraries and I am not sure that my best option should be rewriting everyone else's functions – in those possibly rare occasions when they are written in a way which isn't compatible with ramda – in order to make them work.

**Comment by CrossEye** [comment] 2015-01-19 15:03
@ashnur: I don't have any great answers here.  Ramda was written assuming people would start with fully-written functions and then want to work with them using our utilities; I honestly had never run across anyone doing it the way you describe.

I haven't fully understood the implications of Aadit's proposal here.  It contains some very interesting ideas, and that it would help with your case adds to its weight.  But there are also some significant concerns.  It's going to take a while to digest all this.

**Comment by CrossEye** [comment] 2015-01-20 02:00
I left a comment at https://github.com/ramda/ramda/issues/736#issuecomment-70555440 that seems quite related to this.  I'd appreciate it if those interested in this would read it and respond here or there if they have any related thoughts.

**Comment by TheLudd** [comment] 2015-08-23 07:47
I looked in to this, implemented my own little version of `curry` and I believe this to be the superior version of it. Mainly I think `compose` et al becomes easier to reason about.

Since this has been quiet for a while I wonder where people stand on this. Here is what I concluded that this change will bring about:

 * No varardic functions
 * Compose is changed to:
    ```
      var compose = function(f, g, x,) {
        return f(g(x))
      }
    ```

If this is to be changed, I am sure there will be some problems out there in migrating from the old to the new. Particularly when pipe/compose is used with more than 2 functions at once. I wonder if there are any thoughts on this. Do we want to explore it more? Could we perhaps push an implementation to a branch so that everyone could at least download it and try it out?

**Comment by davidchambers** [comment] 2015-08-23 10:13
In https://github.com/ramda/ramda/issues/1318#issuecomment-132005376 I suggested we have *three* composition functions, none of which is variadic.

**Comment by TheLudd** [comment] 2015-08-23 10:56
> In #1318 (comment) I suggested we have three composition functions, none of which is variadic.

And where does that leave curry? =)

When doing my experimentation, what I realized about compose is that the compose functions that @aaditmshah refer to, not only takes the functions to compose but also the argument to pass to them. So `compose` is not a binary function but a ternary one. Again:

```
var compose = curry(function(f, g, x) {
  return f(g(x))
})
```

This lets us write (provided this version of curry is implemented):
```
// v -> { k: v } -> Boolean
var idEquals = R.propEq('_id')

// v -> [ { k: v } ] -> { k: v }
var findWithId = compose(R.find, idEquals)
```

There is a problem when `g` is a binary function. Example, lets say I want to compose `findWithId` (binary) with a function that returns the property "name". That would not work with the above compose function but it would work with this version that @aaditmshah also mentioned above:

```
var composeBinary = curry(function(f, g, x, y) {
  return f(g(x, y)
})
var findNameForId = composeBinary(R.prop('name'), findWithId))
```

`composeBinary` (or `compose2`) is to me specific, clear and easy to reason about and that is why I like this style. 

Now when we are talking about varardic functions we can talk about them in two ways:

  * **Truly varardic**: the function does not specify parameters and needs to use `arguments`
  * **Semi varardic**: the function takes a specific number of arguments but one of these is an array to avoid the use of `arguments`

In my mind the second is not much better than the first. The arguments in the array are not curriable just as with the fully varardic one. I get a feeling that functions that are **not** varardic at all are always simpler to reason about. I feel this is yet another step in the direction of *simple, not easy*. 

The two versions of compose that I have written here are very specific and not general. It seems to me that when we start to try to solve the general case we go towards *easy, not simple*. But I do beleive that these very specific versions of compose and perhaps one or two more will cover the vast majority of cases we need in our daily lives.

**Comment by aaditmshah** [comment] 2015-08-23 12:46
This is my implementation of `curry` (reference: [How to correctly curry a function in JavaScript?](http://stackoverflow.com/a/27996545/783743)):

```javascript
function curry(f) {
    var length = f.length;
    if (length > 0) return partial(f, length, []);
    else return f;  // f is already curried
}

function partial(f, length, a) {
    return function () {
        var count = arguments.length;
        var arity = length;
        var part  = count < arity;
        var size  = part ? count : arity;
        var args  = new Array(size);
        var index = 0;

        while (index < size) args[index] = arguments[index++];
        if (part) return partial(f, arity - count, a.concat(args));
        var result = f.apply(null, a.concat(args));

        if (typeof result === "function")
            result = curry(result);

        if (arity < count) {
            var args = new Array(count - arity), number = 0;
            while (index < count) args[number++] = arguments[index++];
            return result.apply(null, args);
        }

        return result;
    };
}
```

Using this implementation of `curry` we can write `compose` as follows:

```javascript
var compose = curry(function (f, g, x) {
    return f(g(x));
});

var idEquals = R.propEq("_id");

var findWithId = compose(R.find, idEquals);
```

In addition, we can define `composeBinary` or `compose2` in terms of `compose`:

```javascript
var compose2 = compose(compose, compose);

var findNameForId = compose2(R.prop("name"), findWithId);
```

We can iterate `compose` like this several times (reference: [What does (f .) . g mean in Haskell?](http://stackoverflow.com/a/20279307/783743)):

```javascript
var iterate = curry(function (f, n, x) {
    while (n > 0) x = --n, f(x);
    return x;
});

var compose2 = iterate(compose, 2);
var compose3 = iterate(compose, 3);
// and so on....
```

@davidchambers' `pipe` function could be implemented as the following `chain` function:

```javascript

// data Chain a b where
//     Nil  :: Chain a a
//     Cons :: (c -> b) -> Chain a c -> Chain a b

// The `Chain` data type is a type aligned list isomorphic to @davidchambers' array:
// Chain a b <-> [(c -> b), (d -> c), (e -> d), ..., (t1 -> t2), (t0 -> t1), (a -> t0)]

// chain :: Chain a b -> a -> b
var chain = curry(function (f, x) {
    var l = f.length;
    while (l > 0) x = f[--l](x);
    return x;
});
```

This `chain` function would be considered "semi variadic" if we accept @TheLudd's definition. However, I don't think that's really a problem. Semi variadic functions are better than "truly variadic" functions and we can have semi variadic functions in Haskell as well (the `Chain` data type is a valid Haskell data type).

I agree with @TheLudd that ["truly variadic" functions are a bad code design](http://stackoverflow.com/a/26701110/783743). However, I disagree that semi variadic functions are bad. Such functions can be very useful, like my aforementioned `chain` function which transforms a `Chain` into a function.

**Comment by buzzdecafe** [comment] 2016-03-18 21:32
closed without prejudice

**Closed by buzzdecafe** 2016-03-18 21:32 UTC
Labels: proposal
