### ISSUE TITLE
where(null, {a: 1, b: 2}) returns true

### ISSUE THREAD

**Issue by Cottin** [ramda/ramda#976] opened 2015-03-26 12:42 UTC
I'd expect `where` with `null` passed as first argument to return false but it returns true.

Is it only me who'd expect this?
Would it be an idea to write a line in the docs (http://ramdajs.com/docs/#where) about what to expect if you pass null as the first argument?

`where(null, {a: 1, b: 2}) // returns true`

**Comment by buzzdecafe** [comment] 2015-03-26 13:20
interesting question. It raises some other questions in my mind:

1. why should this work *at all*? I would expect it to blow up
2. why would someone pass a `null` spec?

The fact that it works at all is not by design, it is an artifact of our `keys` implementation which returns an empty array when `Object(obj) !== obj`. This seems reasonable to me. This means that `where(null, test)` is the same as `where({}, test)`, i.e. `true`.

I guess what I'm wondering is question 2 above: why would someone do this? Do you have an example of needing to pass `null` in to `where` for the `spec` object?

**Comment by CrossEye** [comment] 2015-03-26 13:22
I was a little surprised to find that it didn't blow up, and had to see the `keys` implementation to understand it.  But given that it doesn't blow up, this seems the sensible answer.  One way to think about it is that this should be similar to testing with an empty object.  And if that doesn't seem to naturally return true to your mind, think about this example:

```javascript
var data = [
  {name: 'a', a: 1, b: 1, c: 1}, 
  {name: 'b', a: 1, b: 1, c: 2},   
  {name: 'c', a: 1, b: 2, c: 1},
  {name: 'd', a: 1, b: 2, c: 2},   
  {name: 'e', a: 2, b: 1, c: 1},
  {name: 'f', a: 2, b: 1, c: 2},   
  {name: 'g', a: 2, b: 2, c: 1},
  {name: 'h', a: 2, b: 2, c: 2}
];

R.filter(R.where({a: 1, b: 1, c: 1}), data); //=> a
R.filter(R.where({a: 1, b: 1}), data); //=> a, b
R.filter(R.where({a: 1}), data); //=> a, b, c, d
R.filter(R.where({}), data); //=> a, b, c, d, e, f, g,h
```

(See it at http://bit.ly/1HMnPzr.)

This is similar to the mathematical notion of [vacous truth][vt], in which all members of a set are said to automatically hold any particular property if that set is empty.

Does this make sense?


  [vt]: http://en.wikipedia.org/wiki/Vacuous_truth

**Comment by Cottin** [comment] 2015-03-26 14:15
I tried the empty object also and the fact that `where {}, {a: 1, b: 2, c: 3}` returns true is completely what I expected.

I stumbled upon this when I was combining `where` with `find` to get the element a user have selected from a list of possible alternatives. Dumbed down example:

```
render: ->
  selectedObject = find where(@state.selectedObject), possibleAlternatives
  Button selectedObject?.name or 'Please select an object'
```

(Note that that `possibleAlternatives` is an array of objects with many keys and `@state.selectedObject` is an object with less keys).

So, at first render when the user had not selected an object, `@state.selectedObject` would be `null` and I'd want the `Button` to show "Please select and object" but since `where null, ...` returns true, `find where(null), [...]` always returns the first item in `[...]`.

**Comment by CrossEye** [comment] 2015-03-26 17:55
I'm not looking to close this right away, but my first inclination is that this will end up as `WONTFIX`.  The current behavior, even if it came about by happenstance, still seems to me the correct behavior.  The properties of the `spec` object passed to `where` represent predicates, and `where` is simply the conjunction of testing those predicates.

I'm not sure I have a clear enough idea about how your code works to suggest an alternative formulation, but I believe you need to test on whether `@state.selectedObject` is `null` rather than on the result of `find`.  Forgive the JS, I don't know CoffeeScript well:

    var render = R.ifElse(R.isNil, 
                          R.always('Please select an object'), 
                          R.useWith(R.find, R.where, R.identity));

might work.

**Comment by buzzdecafe** [comment] 2015-03-28 12:34
i also think the current behavior is (accidentally?) correct. I'm closing this issue, but feel free to reopen if you want to fight for it.

**Closed by buzzdecafe** 2015-03-28 12:34 UTC
