### ISSUE TITLE
functions have `[String]` signature but also accept `String`

### ISSUE THREAD

**Issue by joaomilho** [ramda/ramda#1800] opened 2016-06-15 11:23 UTC
Apparently some methods, like `omit` and `lensPath` works with only `String` in addition to `[String]`. You can verify this on the docs page by running `R.omit('a', {a: 1, b: 2})` and `R.omit(['a'], {a: 1, b: 2})`, or `R.view(R.lensPath('a'), {a: 1, b: 2})` and `R.view(R.lensPath(['a']), {a: 1, b: 2})`

I suppose this is an unintentional feature, that works because of some inner workings of `_indexOf`, but in any event I think these functions should either reject only `String` or embrace it and add this to the function signatures in the docs. I favor the 2nd approach for it's user friendliness.

WDYT?

**Comment by buzzdecafe** [comment] 2016-06-15 13:28
ugh. it is certainly unintentional, and this seems like a bad thing to me. i would much rather that functions like `omit` and `lensPath` have one API. 

"Never forget that Javascript hates you." --Thomas Reynolds

**Comment by CrossEye** [comment] 2016-06-16 03:41
I'm not overly concerned by accidental implementations that end up reasonably close.  I would not want to document them, because then I would feel we'd have to support them.

I agree with @buzzdecafe that I'd rather have a single API for these, but would not clutter up the implementation with type-checking to ensure that.

I feel similar about 

```js
R.map(x => x.charCodeAt(0), 'foobar'); //=> [102, 111, 111, 98, 97, 114]
```

This is not an appropriate use of `map`, as the output type is not the same type as the input, but it's clear enough what's going on, and we're not committed to it continuing to work this way, as we don't document it or write unit tests for it.  It seems fairly harmless for now.

**Comment by johangirod** [comment] 2017-03-06 16:58
I'm not sure I'm comfortable with this. It might makes sens for `map`, but for functions like `omit`, it's a lot more confusing and can lead to unexpected behaviour really quickly.

For instance : can you predict what the following will do : 
``` js
omit('ab', {'ab': 1, 'b': 1})
``` 
It returns an`{}`. I understand that's a side effect of the internals of ramda, but for `omit`, but it makes it harder to detect errors. Indeed, when I write: 
``` js
omit('ab', {'ab': 1, 'b': 1})
``` 
there's a good amount of chances that what I want to write is: 
``` js
omit(['ab'], {'ab': 1, 'b': 1})
``` 
but no warning or errors are thrown.

If we decide to not break the api with a a stricter type checking, I believe it would be beneficial to have a warning displayed in development.

http://ramdajs.com/repl/#?omit%28%27ab%27%2C%20%7B%27ab%27%3A%201%2C%20%27b%27%3A%201%7D%29

**Comment by davidchambers** [comment] 2017-06-01 02:49
[Sanctuary][1] makes it easier to detect programmer errors by failing immediately when given invalid input. For example:

```javascript
S.test('foo @bar baz', /@\w+/)
// ! TypeError: Invalid value
//
//   test :: RegExp -> String -> Boolean
//           ^^^^^^
//             1
//
//   1)  "foo @bar baz" :: String
//
//   The value at position 1 is not a member of ‘RegExp’.
//
//   See https://github.com/sanctuary-js/sanctuary-def/tree/v0.12.0#RegExp for information about the RegExp type.
```

The Ramda team has decided not to adopt this approach.


[1]: https://sanctuary.js.org/

**Closed by davidchambers** 2017-06-01 02:49 UTC
