### ISSUE TITLE
Release Build process strips extensions from imports

### ISSUE THREAD

**Issue by sebastienfilion** [ramda/ramda#3092] opened 2020-09-28 16:32 UTC
Something in the build process strips every extension from imports.

For example: 
```js
// source/adjust.js
import _concat from './internal/_concat.js';
import _curry3 from './internal/_curry3.js';
```
Becomes:
```js
// source/adjust.js
import _concat from './internal/_concat';
import _curry3 from './internal/_curry3';
```

This is not necessary and it is a problem because it makes it impossible to use the source files with any non-Node runtime. The browser and the Deno runtime requires valid URLs as per ES specification. 

Reference: https://github.com/ramda/ramda/issues/3091

**Comment by Bradcomp** [comment] 2020-09-28 16:40
I'll try to take a look at this.

**Comment by Bradcomp** [comment] 2020-09-28 17:36
Ok, just pulled down the most recent version of Ramda. Cleaned, ran the build and checked the index as well as a smattering of individual files. It doesn't appear to be stripping anything at that point in the game. I checked in the source, src, and es folders after cleaning and building. I also looked at the prepublish script and didn't see anything in there. 

I also looked at the webhook and it looks fine. It also looks like it is pulling from the source folder, which makes sense. 

I can see that as of tag v0.27.1 the extensions are not there. That version clearly went out after the changes to add `.js` were merged. 

I suspect they will be there as of the next release, and potentially we should focus on getting that out. I don't know enough about the actual process of releasing a new version to know if my suspicion is correct. @CrossEye @davidchambers could either of you weigh in on this? Was 0.27.1 an irregular release? Will this get resolved with the next version?

**Comment by davidchambers** [comment] 2020-09-28 17:48
> Was 0.27.1 an irregular release?

No.

> Will this get resolved with the next version?

I don't know, I'm sorry. I automated the release process six years ago (#461), and it worked smoothly for several years. I have not kept up with recent changes to the process; as a result I no longer understand the process. :shrug:

**Comment by CrossEye** [comment] 2020-09-28 21:33
I'm afraid no one has a full handle on the build process now.  It might be simply time for a rewrite.

**Comment by Bradcomp** [comment] 2020-09-28 22:53
Looking at the commit for the tag here: https://github.com/ramda/ramda/commit/6bb8eeaabbe130cc4f9860e9124ae69320636fcd

When I click on the parent it takes me here: https://github.com/ramda/ramda/commit/ed191e6a476330e37db259a5c2d04bfba0b2d63d

That's a pretty old commit. I'm not a git wizard but it doesn't look like the difference between those two encompasses all the changes over that year? How do we go about getting changes from master into a tagged release?

**Comment by sebastienfilion** [comment] 2020-09-28 23:12
@Bradcomp Like this: https://github.com/ramda/ramda/compare/v0.27.0...v0.27.1
I do feel like something is missing between 0.27.0 and 0.27.1

**Comment by sebastienfilion** [comment] 2020-09-28 23:13
The changes between 0.27.0 and HEAD has the missing commits... https://github.com/ramda/ramda/compare/v0.27.0...HEAD

**Comment by davidchambers** [comment] 2020-09-29 07:52
See <https://github.com/ramda/ramda/issues/3062#issuecomment-665864256> for context, @Bradcomp. I rereleased [v0.27.0][1] as [v0.27.1][2], being careful to exclude subsequent commits.


[1]: https://github.com/ramda/ramda/releases/tag/v0.27.0
[2]: https://github.com/ramda/ramda/releases/tag/v0.27.1

**Comment by davidchambers** [comment] 2020-09-29 08:07
> > Was 0.27.1 an irregular release?
>
> No.

I believe I misunderstood your question, @Bradcomp, and gave you the wrong answer as a result. It *was* an irregular release: it was not made from the head of `master`. (I created [v0.27.1][1] by running `make release-patch`, but I believe you are interested in the commits that were included in v0.27.1 rather than the way in which it was released.)


[1]: https://github.com/ramda/ramda/releases/tag/v0.27.1

**Comment by CrossEye** [comment] 2020-10-01 23:30
@Bradcomp: absolutely.  I always need to find the process again.  I can't seem to keep it in my head.  But we can work it out.

**Comment by hitmands** [comment] 2020-10-07 20:36
this was once implemented here https://github.com/ramda/ramda/pull/3042 by @sebastienfilion, 
probably a regression at this point.

**Comment by sebastienfilion** [comment] 2020-10-18 23:54
@Bradcomp @CrossEye have you guys got the chance to talk about a new release?

**Comment by CrossEye** [comment] 2020-10-19 13:03
@sebastienfilion: We haven't, I'm afraid.  But if we haven't done it before then, I will try to find time next weekend.

**Comment by sebastienfilion** [comment] 2020-11-14 16:24
@Bradcomp @CrossEye Is there something I can do to help this move forward?

**Comment by quilicicf** [comment] 2020-12-07 20:25
In the meantime, it's possible to use the URLs to the raw files on GitHub (like [this](https://raw.githubusercontent.com/ramda/ramda/master/source/add.js)) but it is a hack :-( 

It'd be nice to have a working tag on deno.land. :pray:

**Comment by sebastienfilion** [comment] 2020-12-08 14:39
> In the meantime, it's possible to use the URLs to the raw files on GitHub (like [this](https://raw.githubusercontent.com/ramda/ramda/master/source/add.js)) but it is a hack :-(
> 
> It'd be nice to have a working tag on deno.land. 🙏

There's a working tag on Nest.land, if that helps in the meantime... `https://x.nest.land/ramda@0.27.0/source/index.js`

**Comment by sebastienfilion** [comment] 2020-12-15 12:54
@CrossEye 
Because, the information about Deno in the README is not working as expected and leading users astray; Would you authorize me to publish to Ramda's Deno repository from my fork to by-pass this issue temporarily. We did this together a few months ago https://github.com/ramda/ramda/issues/3074

**Comment by sebastienfilion** [comment] 2020-12-15 13:43
@CrossEye 
Because, the information about Deno in the README is not working as expected and leading users astray; Would you authorize me to publish to Ramda's Deno repository from my fork to by-pass this issue temporarily.

**Comment by CrossEye** [comment] 2020-12-15 15:23
Certainly.  AFAICT, that webhook is still active but has never been triggered.  Is there something else we need to do?

**Comment by sebastienfilion** [comment] 2020-12-15 16:00
@CrossEye Maybe deactivate your webhook to avoid issues until we figure out this build issue. My repository will take over in the meantime.

**Comment by CrossEye** [comment] 2020-12-15 19:21
@sebastienfilion : done

**Comment by sebastienfilion** [comment] 2020-12-21 18:53
I've republished to Deno/x and Nest and fixed the README in accordance. https://github.com/ramda/ramda/pull/3123

**Closed** 2022-01-19 02:34 UTC
