### ISSUE TITLE
R is not defined(…) on docs page

### ISSUE THREAD

**Issue by slavaGanzin** [ramda/ramda#1853] opened 2016-08-06 14:24 UTC
Hello everyone.
It starts a week or two ago:

*steps to reproduce*
1. goto http://ramdajs.com/docs/
2. Open developer console
3. Type R and press Enter
```
VM103:1 Uncaught ReferenceError: R is not defined(…)
```

*but*
1. goto http://ramdajs.com/repl/?v=0.21.0
2. click documentation
3. Open developer console
4. Type R and press Enter
```
Object {__: Object}
```

**Comment by buzzdecafe** [comment] 2016-08-07 02:38
hmmm, seems to be working fine here:

![screenshot_20160806_223723](https://cloud.githubusercontent.com/assets/716260/17460136/85cd62f8-5c26-11e6-82ae-e738719d68b4.png)

**Comment by ntkoso** [comment] 2016-08-07 03:14
I can reproduce this on `Chrome 52` .
When you go to http://ramdajs.com/docs/ directly, `R` is missing.
It shows up after a page refresh.
On `Firefox 48` it works fine.

**Comment by buzzdecafe** [comment] 2016-08-07 04:34
curious. (also this issue belongs on docs repo)

**Comment by davidcalhoun** [comment] 2016-08-07 06:50
I also have this issue, and it does seem to resolve itself on refresh.  Strange.

**Comment by buzzdecafe** [comment] 2016-08-07 12:40
atm i don't see what the site can do about this -- ramda is included in `docs/index.html` like so:

`<script src="dist/ramda.js"></script>`

and the file is there. Are there any chrome bug reports on this strange behavior? (I also note that it works fine in Chrome 49)

**Comment by ecwyne** [comment] 2016-08-10 22:37
I've noticed this recently in Chrome DevTools in my Meteor projects. Globally scoped objects aren't added unless you have the console open BEFORE you load the page.

To Fix:

1. Go to http://ramdajs.com/docs/
2. Open the javascript console
3. REFRESH the page

**Comment by buzzdecafe** [comment] 2016-08-11 12:53
> Globally scoped objects aren't added unless you have the console open BEFORE you load the page.

yikes. so this is looking more and more like a chrome bug. i've taken a few looks for a bug report on this issue but have come up empty so far.

**Comment by fix-fix** [comment] 2016-08-19 11:43
I think you encountered [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=613878) in Chrome. In the current version (v52 at the time of writing) Chrome tries to guess which frame use as a context for developer console, and sometimes it's set to the frame of some extension instead of 'top' (current document frame).
It has been fixed, so you can try to reproduce your problem in Chrome Canary.

If that is the case, this issue should be closed, because it's not related to Ramda.

**Comment by buzzdecafe** [comment] 2016-08-19 13:24
thanks @fix-fix ; i am closing this since it seems clear that this is not the docs sites problem. if anyoine can demonstrate that it is, please reopen

**Closed by buzzdecafe** 2016-08-19 13:24 UTC

**Comment by davidcalhoun** [comment] 2016-08-22 01:40
I can confirm that it's no longer a problem in Canary!  Tested in Version 54.0.2835.0 canary
