### ISSUE TITLE
Merge breaking change

### ISSUE THREAD

**Issue by davidebianchi** [ramda/ramda#1560] opened 2015-12-22 16:51 UTC
I noticed a (undocumented) breaking change in the `R.merge` function between `v0.18.0` and `v0.19.0`. 

Reproduction:

``` js
R.merge({a: 5}, undefined)
```
- [Behaviour in `v0.18.0`](http://bit.ly/1YyX7la)
- [Behaviour in `v0.19.0`](http://bit.ly/1YyWJTU)

As soon as I have a bit of time I'll try to figure out the cause of the regression and prepare a PR for it. For now, I'll just open the issue. :smiley:

**Comment by davidchambers** [comment] 2015-12-22 18:10
Though this is a behaviour change, I don't consider it a regression. `R.merge` was not and is not documented to accept `null` or `undefined`: it operates on two objects. The previous implementation *happened* to treat `undefined` as equivalent to `{}` due to its use of `keys`, which for some reason does not throw when applied to `undefined`.

This is a situation where [sanctuary-def][1]-style type checking—discussed in #1125—would have prevented a "regression" by not allowing the invalid use in the first place.


[1]: https://github.com/plaid/sanctuary-def

**Comment by davidebianchi** [comment] 2015-12-22 22:59
Hi @davidchambers,

good point. Without type-checking it is indeed difficult to know/predict whether or not the function will be called correctly (unfortunately `undefined` is often slip through).

Right now though `R.merge` has an [inconsistent behaviour when it comes to non objects](http://bit.ly/1MuyTS8), which makes using it fairly confusing.

I would suggest either adding a runtime type check - like in the case of `R.test` - or defaulting the input parameters to the empty object in case they are not objects to begin with, sort of how `R.keys` defaults to the empty array if its input is not an object.

**Comment by davidchambers** [comment] 2015-12-24 22:23
I'll let @CrossEye respond to this. My position on run-time type checking is well documented. ;)

**Comment by CrossEye** [comment] 2016-01-02 21:51
Sorry, just catching up on some old issues.

While I agree that this is not technically a regression, as we didn't document any behavior for non-objects, I believe the 0.18 behavior is what we would prefer.  I especially like this:

> defaulting the input parameters to the empty object in case they are not objects to begin with, sort of how `R.keys` defaults to the empty array if its input is not an object.

**Comment by davidchambers** [comment] 2016-01-03 00:57
> I especially like this:
>
> > defaulting the input parameters to the empty object in case they are not objects to begin with, sort of how `R.keys` defaults to the empty array if its input is not an object.

I'm not fond of ad hoc polymorphism. `R.keys(null)` is a type error, as far as I'm concerned. ;)

**Comment by CrossEye** [comment] 2016-01-03 01:06
```js
typeof null; //=> "object"
```
:smile:

This is definitely something on which we disagree.  I think that we should most often be able to give reasonable behavior when `null` or `undefined` is supplied in place of an object.  To me we should do so in these cases.  Since `null` has no keys, `R.keys(null)` should simply return `[]`.

**Comment by buzzdecafe** [comment] 2016-01-03 01:15
c'mon @CrossEye, in any reasonable language `keys(null)` would be a type error. Or `null` would not exist. But here we are

**Comment by davidchambers** [comment] 2016-01-03 01:18
> Since `null` has no keys, `R.keys(null)` should simply return `[]`.

Similarly, `R.inc('XXX')` should evaluate to `NaN` presumably?

The problem with failure values such as `NaN` is they allow failures to propagate *implicitly*. I'd prefer either to be forced to handle failures explicitly, or to have my program crash so I know what needs fixing. :)

**Comment by CrossEye** [comment] 2016-01-03 02:31
> c'mon @CrossEye, in any reasonable language `keys(null)` would be a type error. Or `null` would not exist. But here we are

Yes, here we are, writing a Javascript library for Javascript developers.  This is one of those places where I don't think the behaviours from other languages are particularly relevant.

**Comment by CrossEye** [comment] 2016-01-03 03:15
>> Since `null` has no keys, `R.keys(null)` should simply return `[]`.

> Similarly, `R.inc('XXX')` should evaluate to `NaN` presumably?

I don't see it myself.  I see a function as answering a question more than performing an operation.  `keys(val)` answers the question "What are the keys of `val`?"  `inc(n)` answers the question "What is the successor to `n`?"  The first question has a reasonable answer for many values other than the expected input, and I have no problem supplying that.  The second one generally doesn't, although clearly we might find non-integer data types for which it is, in fact, appropriate.

What are the keys of `null`?  Well, it doesn't have any.  Neither does `{}`.  They deserve the same answer as far as I can tell.  The alternative is an exception.  I'm very loathe to throw exceptions.  Exceptions do not compose.  They return the answer "Hey, dummy, you don't know what you're doing here!"  To me, that's only acceptable when there is no reasonable alternative.

Such is the case with `inc('XXX')`.  There is no reasonable answer.  There is no successor to 'XXX', and `NaN` certainly is not a useful answer to that question.  That might fall out of an implementation, and we might live with it, but it should never be considered desirable or correct behavior.  Nor should the current behaviour, `inc('XXX'); //=> '1XXX'`.  Here I would absolutely consider throwing as a possible last resort.

> The problem with failure values such as `NaN` is they allow failures to propagate *implicitly*. I'd prefer either to be forced to handle failures explicitly, or to have my program crash so I know what needs fixing. :)

That's really useful for a certain style of application, and a certain kind of data.  It works well if you have reasonably fixed inputs that you can readily recreate, something like batch jobs, or well-logged server-side work.  If you have to work with user-facing applications and inconsistent -- perhaps even incoherent -- input streams, then code that will crash an application unnecessarily is simply a hazard.  You won't appreciate that `keys(null)` throws an exception if there is a possible `null` supplied to `keys` when, "Well, I had put fourteen items in my shopping cart, then deleted numbers three, seven, and nine, but added back number seven twice before dragging the coupon from the other window (did I mention the coupon already?) to the coupon box, and typing in my credit card number but not tabbing out of the field, merely clicking on the submit button.  This doesn't happen every time, mind you, but at least every fifth time I try it.  It seems more likely to happen if I have both GMail and Facebook open in other tabs, but that might be just coincidence."  In that situation, if the code can recover well enough to proceed without obvious error, without an application-crashing exception, then you're probably much happier.

**Comment by davidchambers** [comment] 2016-01-03 03:28
I'm very pleased not to be responsible for debugging that shopping cart bug. :stuck_out_tongue_winking_eye:

**Closed** 2017-10-17 12:45 UTC
