### ISSUE TITLE
uniq is slow

### ISSUE THREAD

**Issue by krzychukula** [ramda/ramda#1500] opened 2015-11-06 10:24 UTC
We had to replace:
```
var getIds = R.map(R.path(['id']));
var oneIds = getIds(listOne);
var twoIds = getIds(listTwo);
var ids = R.uniq(R.concat(oneIds, twoIds));
```
with:
```
var idsHash = {};

listOne.forEach(function(item) {
          idsHash[item.id] = 1;
});

listTwo.forEach(function(item) {
          idsHash[item.id] = 1;
});

var ids = Object.keys(idsHash);
```

The former for big amounts of data blocked node event loop for ridiculous amouts of time (something like 25minutes).

Did I misuse uniq?

**Comment by honzabrecka** [comment] 2015-11-06 10:59
Yes, it's slow because it uses many while cycles O(n) whereas you are using a hash map O(1).

**Comment by krzychukula** [comment] 2015-11-06 11:04
@honzabrecka I realized that :) Imho it's a bug, but maybe there is a reason that it's not possible to fix without breaking api? 
I would expect uniq to be O(1)...

**Comment by iofjuupasli** [comment] 2015-11-06 11:24
> I would expect uniq to be O(1)...

But it just impossible for two lists.

O(1) possible only for checking one value in hash map.
When you have many values and hash - you have O(n), where n is length of values list.
With two lists you should compare each value O(n1) from list two with list one O(n2), and only if its uniq insert it O(1). So resulting complexity is O(n1 * n2).
In case when you can use hash map (you have uniq string keys), then you can insert O(1) each value from list one O(n1) to hash and then same for list two O(n2). Resulting complexity is O(n1 + n2). Which is much better.

But uniq doesn't know that you can use hash keys.

However it seems possible to create such method.

**Comment by krzychukula** [comment] 2015-11-06 12:10
Sorry, I don't get why you have to get O(n1 * n2) complexity :(
Why it can't always treat values as hashable? Can you give me an example?

**Comment by CrossEye** [comment] 2015-11-06 13:51
I've known for a while that `uniq` is slow.  It's been mentioned before, and I've been bitten by it myself.  It's on my list.  The real trouble is that Ramda is checking for value equality, not reference equality.  Even its `O(n^2)` algorithm would be substantially faster if we would allow ourselves the luxury of comparing references only.  But that's not the Ramda way.

Probably the best bet would be to find a good way to hash values.  The most likely candidate is our `toString` implementation, but I don't know just how robust it is.  Perhaps @davidchambers can tell us if he thinks it's up to this job.

Even with that, it still would not be as quick as reference equality implementations, but it should give a very substantial boost.  Anyone feel like trying this?

**Comment by buzzdecafe** [comment] 2015-11-06 13:55
yeah in order to get *O(2n)* we need a reliable way to map equivalent objects to identical string keys.

**Comment by asaf-romano** [comment] 2015-11-06 14:36
I've been playing with something like ``R.pipe(R.groupBy(R.toString), R.map(R.uniq), R.flatten)`` in some other issue and got very bad results :-/

**Comment by CrossEye** [comment] 2015-11-06 14:39
I did a `uniq` on some 45,000 objects, folding into 150 unique values and it took about 30 seconds.  We clearly need to fix this.

**Comment by buzzdecafe** [comment] 2015-11-06 14:47
here's a try: http://bit.ly/1MMWeVO

**Comment by asaf-romano** [comment] 2015-11-06 14:48
@CrossEye Mind trying ``R.pipe(R.groupBy(R.toString), R.map(R.uniq), R.flatten)`` on that set?

**Comment by asaf-romano** [comment] 2015-11-06 14:49
If it's as slow as I remember, there's very little that can be done, I think.

**Comment by niloy** [comment] 2015-11-06 15:14
Using `uniqWith((a, b) => a === b, list)` does solve the problem?

**Comment by raine** [comment] 2015-11-06 15:16
@nilou, https://github.com/ramda/ramda/issues/1449

**Comment by davidchambers** [comment] 2015-11-06 17:18
`R.toString` shouldn't be relied upon for function values, but otherwise it should be sound. I rely on it in my test suites:

```javascript
const eq = (act, exp) => {
  assert.strictEqual(arguments.length, 2);
  assert.strictEqual(R.toString(act), R.toString(exp));
};
```

**Comment by niloy** [comment] 2015-11-06 18:10
There is something about `R.identical` that just messes up the JS engine. I compared `R.identical` with plain function `(a, b) => a === b`. Plain function is way faster on my machine.

```js
var arr = R.times(Math.random, 20000);

console.time('identical');
R.uniqWith(R.identical, arr);
console.timeEnd('identical'); // 154s

console.time('plain function');
R.uniqWith(function(a, b) {
  return a === b;
}, arr);
console.timeEnd('plain function'); // 7s
```

The bottle neck is `R.identical`. So just using a plain function should give instant perf boost.

**Comment by CrossEye** [comment] 2015-11-06 18:34
@asaf-romano: It was a one-off.  I'll look around to see if I still have the data.

@niloy: That's fine if you're doing reference equality, but doesn't help with value equality.

Also, there are reasons that `identical` is different from `(a, b) => a === b`:

```js
R.uniqWith(R.identical,       [+0, -0, 1, NaN, 2, 3, NaN]); //=> [0, -0, 1, NaN, 2, 3]
R.uniqWith((a, b) => a === b, [+0, -0, 1, NaN, 2, 3, NaN]); //=> [0, 1, NaN, 2, 3, NaN]
```

It's simply different behavior.

**Comment by asaf-romano** [comment] 2015-11-07 15:22
The performance issue isn't related to === vs Object.is/R.identical. I'm afraid I've some bad news about R.curry; will open an issue in a bit.

**Comment by krzychukula** [comment] 2015-11-09 13:27
Hi,

Imho identical or curry are not the biggest issue here. The only thing that can help really is hasing values (sacrifice memory for speed).
http://jsperf.com/ramda-uniq-performance
It's not super clear but when you compare the same invocations with 2x times more data you can see that it takes longer ~4x. It's basically exponential. 
Data I had: 200000 string ids: It's way to much to even put into JSPerf - I am not patient enough to wait for it in JSPerf - that's why I have used smaller numbers to show you the trend.

I would advocate that if it's not really solvable while preserving value equality (I'm don't know enough about that part to have any idea) then I would advoate to remove it from API or display fair warning about lack of scalability of uniq funcitons. That may sound really bad but in my opinion it's better to have API users can depend on or use knowing it's limitations :)

**Comment by iofjuupasli** [comment] 2015-11-09 13:48
lodash uses Set for big arrays to check uniq keys. I think you guys should just use this implementation as much as possible https://github.com/lodash/lodash/blob/master/lodash.js#L3393

**Comment by CrossEye** [comment] 2015-11-09 13:52
@iofjuupasli:
> lodash uses Set for big arrays to check uniq keys

lodash is not worried about value equality, only reference equality.  There are a number of good solutions for that.

The problem is that Ramda insists that `{a: 1, b: 2}` and `{a: 1, b: 2}` are equal even if they don't refer to the same instance in memory.  It's a useful, and important, stance to take, but it means that, as @krzychukula says, likely our only bet to speed this up is a hash.  And @buzzdecafe's early experiments with the only likely hash we have around, `R.toString`, are not encouraging.

**Comment by iofjuupasli** [comment] 2015-11-09 13:56
But when value is string or number? https://github.com/lodash/lodash/blob/master/lodash.js#L1944
For most usages of `uniqBy` and for TS case it should works.

**Comment by CrossEye** [comment] 2015-11-09 15:34
We've been discussing `uniq`/`uniqWith`.  I agree that `uniqBy` could well work with Sets in environments that support them.  Alternatively, I would really not have an issue with changing the signature to 

```js
uniqBy :: (a -> String) -> [a] -> [a]
          (a -> Number) -> [a] -> [a]
```

That would clean things up quite a bit.

**Comment by davidchambers** [comment] 2015-11-09 19:08
Why `a -> (String | Number)` rather than `a -> String`? I don't like to rely on implicit type coercion.

**Comment by CrossEye** [comment] 2015-11-09 21:17
Just easily imagining

    uniqBy(identity, numbers)

rather than

    uniqBy(String, numbers)

This isn't something I'm wedded to, by any means.  But would you do a type-check on every call to this function?  If not, then even if documented as `(a -> String)`, a function that was actually `a -> Number` would probably work through the language's implicit coercion, so long as you didn't mind that `"7"` and `7` are to be considered the same.

My first attempt to create one was embarrassingly slower than the alternatives: linear, but with really large coefficients, it seems.  I haven't spent significant time on this, though, just something to occupy my mind during an otherwise unproductive meeting.

**Comment by asaf-romano** [comment] 2015-11-10 07:24
FWIW, The very same issues issues apply to ``R.difference`` (at least). For a ``(5000 **all strings** ,5 *all strings**)`` call, I got 100% cpu usage for over 13 seconds on a very fast iMac. I got away by introducing an *identical version of the function, that uses Set, similar to uniqIdentical discussed elsewhere and the like.

Demo:
library difference: http://bit.ly/1WOhOsr   (13491ms for me)
set-based difference: http://bit.ly/1WOi7U6  (3ms for me)

**Comment by asaf-romano** [comment] 2015-11-10 07:28
All of this makes me wonder if it's worth introducing functions like ``uniq.homogeneous``, ``difference.homogeneous`` etc, in which the contract requires that all elements in the collection are of the same shape. These functions can then at least optimize the primitive-values cases, which are very common (well, at least in my code base). I think that with value based equality, different shapes assumption and lack of proper hashCode in js, there's very little that can be done otherwise.

**Comment by scott-christopher** [comment] 2015-11-21 20:45
#1512 has just landed in master which should help to resolve this issue. If you'd like to test on master, please run `npm run build` before requiring `dist/ramda`.

Closing this for now. Please reopen if it still seems to be an issue.

**Closed by scott-christopher** 2015-11-21 20:45 UTC

**Comment by Restuta** [comment] 2017-10-05 15:12
It seems to still be an issue:

sample code:

```js
const R = require('ramda')
const _ = require('lodash')

const randomNumbers = R.range(1, 4001)
  .map(x => ({x: Math.random()}))
  .concat(R.repeat({x: 8}, 100))


const measureTime = (name, func) => {
  console.time(name)
  const results = func()
  console.timeEnd(name)

  return results
}

const resultsR = measureTime('ramda', () => R.uniq(randomNumbers))
console.log(resultsR.length)

const resultsLo = measureTime('lodash', () => _.uniq(randomNumbers))
console.log(resultsLo.length)
```

output:

```
ramda: 24572.116ms
4001
lodash: 4.880ms
4001
```

```
node -v
v8.4.0
```

**Comment by scott-christopher** [comment] 2017-10-05 21:02
@Restuta You can achieve similar times when using `R.uniqWith((x, y) => x === y)` instead.

```
ramda uniqWith: 6.982ms
4000
lodash: 4.592ms
4000
```

To emphasise the difference in functions, changing your `randomNumbers` to a constant but non-identical `{x: 8}` ...
```
const randomNumbers = R.range(1, 4001).map(x => ({x: 8}))
```
... produces 1 unique element with `R.uniq` and 4000 unique elements for the other two:
```
ramda: 23.973ms
1
ramda uniqWith: 7.414ms
4000
lodash: 4.929ms
4000
```

**Comment by Restuta** [comment] 2017-10-05 23:31
@scott-christopher true, I should have explained that I understand the difference, but thank you anyway. My concern is that uniq feels slow by default. I wonder why so. 

I'd understand if each object had a lot of properties or deep nested ones, but for such a simple case with 4000 objects 20s seems very harsh.

**Comment by scott-christopher** [comment] 2017-10-06 01:10
Generating 4000 unique objects will end up making ~8,000,000 `R.equals` comparisons (n(n-1)/2). This is a large reason why other functions like `R.uniqBy` exists, where the performance can be optimised (often to log(n)) for a given user's scenario.

However, where it looks like there is some room for improvement is with `R.equals`, as testing the various combinations of `R.uniqWith`, `_.uniqWith`, `R.equals` and `_.isEqual` shows:

```
R.uniqWith(R.equals, randomNumbers): 21932.915ms
4001
R.uniqWith(_.isEqual, randomNumbers): 6438.672ms
4001
_.uniqWith(randomNumbers, _.isEqual): 6341.493ms
4001
_.uniqWith(randomNumbers, R.equals): 23309.969ms
4001
```

If you feel like taking a look, any optimisations there would likely be welcome.

**Comment by CrossEye** [comment] 2017-10-07 02:51
It does look like there is some optimization to be done.  There are some API differences -- the handling of Primitive wrappers, and `+0` and `-0`, for instance -- but none of them look likely to be worth a three or four-fold difference.

**Comment by Restuta** [comment] 2017-10-12 14:29
@scott-christopher yes, that is exactly my point, thanks for providing a better example. @CrossEye worth re-opening the issue then?

**Comment by CrossEye** [comment] 2017-10-12 17:19
@Restuta: I would rather a new issue around fixing _equals_.  Feel free to open one and point to this discussion.
