### ISSUE TITLE
ES6 code in ramda builds

### ISSUE THREAD

**Issue by char0n** [ramda/ramda#2713] opened 2018-11-25 15:17 UTC
Some of the new v0.26.0 release functions contains directly ES6 block scoped variable declarations with `const` keyword. Later when the ramda get's babelified (es/, lib/) those declarations are not changed to `var`. This effectively means that ramda@0.26.0 and higher are ES6>= compatible. It's no longer ES5 code. It will not run in phantomjs, older IEs or older node installations. Is that something that was intended or it has only slipped inside by chance ? I'm just wondering; if the conscious decision has been made, that we need to compensate in our environments.

Problem can be seen in  `pipeWith` function here https://github.com/ramda/ramda/blob/master/source/pipeWith.js#L35 in sourcecode and here https://npm.runkit.com/ramda/es/pipeWith.js?t=1543159000862 on npm distribution

**Comment by davidchambers** [comment] 2019-04-29 09:27
Can you update us on this issue, @CrossEye?

**Comment by CrossEye** [comment] 2019-04-30 14:07
The update is that I totally forgot this issue.  I will try to look into it as soon as I can.

**Comment by customcommander** [comment] 2021-12-24 16:14
Seems like issue #2803 is a duplicate of this one?

**Comment by char0n** [comment] 2021-12-27 07:33
This is no longer issue in [v0.27.1](https://npm.runkit.com/ramda/es/pipeWith.js?t=1640590264599). IMHO we can close this issue.

**Comment by customcommander** [comment] 2021-12-27 09:52
Thanks @char0n :)

**Closed by customcommander** 2021-12-27 09:52 UTC
