### ISSUE TITLE
chain test - 'interprets ((->) r) as a monad' is failing

### ISSUE THREAD

**Issue by sagifogel** [ramda/ramda#2008] opened 2016-12-11 23:45 UTC
```
 it('interprets ((->) r) as a monad', function() {
    var h = function(r) { return r * 2; };
    var f = function(a) {
      return function(r) {
        return r + a;
      };
    };
    var bound = R.chain(f, h);
    // (>>=) :: (r -> a) -> (a -> r -> b) -> (r -> b)
    // h >>= f = \w -> f (h w) w
    eq(bound(10), (10 * 2) + 10);
}); 
```
The arguments `R.chain(f, h)` sent to the bound function created by R.chain should be switched.
The bound function should be created using `R.chain(h, f)`.
Currently an exception will be thrown when invoking the bound function. When you switch the arguments you get the expected result - 30.

**Comment by buzzdecafe** [comment] 2016-12-22 16:41
duplicate of https://github.com/ramda/ramda/pull/1937

should be fixed whenever next release happens

**Closed by buzzdecafe** 2016-12-22 16:41 UTC
