### ISSUE TITLE
Currying with default argument values short-circuit currying

### ISSUE THREAD

**Issue by sugoidesune** [ramda/ramda#3121] opened 2020-12-18 23:42 UTC
```js
    var p = R.curry((x,k,c='koko',d)=>console.log(x,k,c,d))
    
    p('haha') // properly waiting for second argument
    p('haha','love') // shortcircuits and calls the full function.
    //>>> haha love koko undefined
````
Rather unexpected behavior.
I wish the docs at least would mention this.
I am not sure if this is at all fixable.

**Comment by CrossEye** [comment] 2020-12-19 02:28
Duplicate of #3105

**Comment by CrossEye** [comment] 2020-12-19 02:30
If you have suggestions for how this should be documented, I would love to hear it

But it's fairly fundamental behavior to both default parameters and for Ramda, and is not likely to be changed.

**Comment by sugoidesune** [comment] 2020-12-19 02:49
Adding a note explaining this behavior would be fine/linking to one of the issues/ blogpost.
And possibly offering a ramdean replacement pattern.
Spent quite some time looking for the bug, because it's the last thing I expected to change its behavior.

**Comment by sugoidesune** [comment] 2020-12-19 03:41
I suppose the best way would be to use R.curryN
````js
var p = R.curryN(4,(x,k,c='koko',d)=>console.log(x,k,c,d))
````

**Comment by CrossEye** [comment] 2020-12-21 03:01
@sugoidesune:

> Adding a note explaining this behavior would be fine/linking to one of the issues/ blogpost.

Are you interested in creating a PR for this?

> I suppose the best way would be to use R.curryN

But then your derived function couldn't use the default parameter.  While I guess that this would work in cases where you need the defaulting behavior in the underlying function, but want the Ramda-curried one to require all arguments be eventually specified.  But that seems like a fairly obscure corner-case.

The entire design of Ramda's currying is to require the user to supply all parameters, but allow her to supply them gradually.  A function with a default parameter is designed to allow her not to supply certain parameters.  I can't think of a reasonable way to mix the two notions.

**Comment by sugoidesune** [comment] 2020-12-22 15:13
True. If you want to be able to call a function with arity 3 with only 2 arguments, because the last has a default, then this shortcircuiting behavior might be desired. The optional arguments should be then always last.

If multiple arguments have defaults and youre trying to partially apply them, then this is unwanted.

> Are you interested in creating a PR for this?
Sure. Will take a look how to ramda-docs :)

**Comment by CrossEye** [comment] 2022-01-19 02:20
Pinging @sugoidesune: Are you still interested in creating a documentation PR?  If so, the documentation is simply generated from the JSDoc tags in the source file, so you can just edit that.

**Closed** 2022-02-26 19:03 UTC
Labels: documentation
