### ISSUE TITLE
Misleading documentation for R.and

### ISSUE THREAD

**Issue by amsross** [ramda/ramda#1979] opened 2016-11-16 11:34 UTC
I can open a PR for this, but I thought it prudent to first make sure that it is what I think it is.

The documentation for `R.and` states that it it "Returns `true` if both arguments are `true`; `false` otherwise." In actuality, it returns the second argument if both arguments are truthy otherwise the falsey argument:

```
R.and(true, null); // null
R.and(null, true); // null
R.and(true, 1); // 1
R.and(1, true); // true
```

I stumbled over this myself once and followed this being discussed in Gitter twice, so I thought it was worth having addressed. In each of these cases, the docs are being read to imply that there is some `===` or type checking going on, when it is just a logical `&&`.

Apparently [this change](https://github.com/ramda/ramda/commit/c6ee561433467cef6086ecbc43969d9d24c265af#diff-b30d8dbbbdd736dc03d20f64e76c97bc) was made to simplify this logic. While I don't there is any issue with having done that, I do think that the docs are no longer representative of what the function does.

**Comment by CrossEye** [comment] 2016-11-16 13:34
Please see #1971.

**Comment by amsross** [comment] 2016-11-16 13:47
Ok, thanks for pointing me there. I looked through the issues to make sure this wasn't a duplicate, but didn't think to check PRs.

**Comment by CrossEye** [comment] 2016-11-16 14:57
Oh, no problem at all.  We have far too many irons in the fire right now.

**Comment by jay-jlm** [comment] 2018-02-25 18:42
Please consider reopening this.
It still reads:
`Returns _true_ if both arguments are _true_; _false_ otherwise`
.. this is not a correct statement if the function can ever return values other than _true_ or _false_, which it does in certain cases.

**Comment by CrossEye** [comment] 2018-02-26 15:14
There was such a kerfuffle about this that I'm loathe to revisit it.  But I could live with changing to something like

```js
const and = (a, b) => Boolean(a && b)
```

It's not what I'd prefer, but I am tired of revisiting this.  Others?

**Comment by davidchambers** [comment] 2018-02-26 15:28
> It's not what I'd prefer, but I am tired of revisiting this.

Ramda needs more guiding principles. Such discussions will continue to arise until there is a clear vision for the relationship between type signatures and the handling of invalid inputs.

**Comment by polytypic** [comment] 2018-02-26 20:49
> Ramda needs more guiding principles.

Couldn't agree more.  I've been using Ramda in all of my JS projects, but I find it very unfortunate that Ramda doesn't seem to have a simple consistent philosophy when it comes to handling unexpected inputs.

For example, in 0.25.0 `R.prop('x', null) ~> undefined`, but `R.propEq('x', 'y', null) ~> raises Error`.  However, earlier (in 0.24.0) `R.prop('x', null) ~> raises Error`.  Would I tell my friends that they can trust that `R.prop('x', null)` continues to return `undefined`?  I really shouldn't.  Might Ramda someday decide `R.propEq('x', anythingExceptUndefined, null) ~> false`?  I have no idea.

Ramda seems to be designed with only the "happy path" in mind, but in real projects I need to write code that does something consistent even in unfortunate and more challenging scenarios.

Let's consider something as simple as `R.prop`.  Sometimes I want my code to raise an error or otherwise signal a failure in case the target isn't an object.  Right now in 0.25.0 I have to do that explicitly.  That is OK.

On the other hand, I might be implementing some sort of search algorithm and use `R.prop` as a part to attempt to extract a property from something that might or might not be an object.  Right now in 0.25.0 I could rely on the fact that `R.prop` returns `undefined`.  That is OK, too.

However, I feel I really shouldn't make such assumptions and I find that very unfortunate for a couple of reasons.  First of all, it is very easy to accidentally write code that makes such assumptions (based on the current observed behaviour).  This basically sets up a time bomb.  Every time the behaviour of `R.prop` changes, there is a change that code breaks, because someone relied on such accidental behaviour.  On the other hand, not being able to rely on anything but the happy path behaviour means that many use cases have to add extra defensive code around uses of `R.prop` to behave consistently.  Neither of these is OK, IMHO.

Also, a lot of Ramda is even worse than `R.prop` in the sense that unexpected inputs are actually treated in pure GIGO fashion like with [`R.omit('string')`](https://github.com/ramda/ramda/issues/2330).

So, please, formulate a clear policy for Ramda on how it deals with unexpected inputs.  Raise errors consistently.  Or return some arguably sensible default consistently.  Or a carefully considered combination of raising errors and returning sensible defaults (which is what I'd do myself).  Or do GIGO consistently with no attempt to handle unexpected inputs (which I wouldn't like myself - I'd probably decide to stop using Ramda at that point, but at least it would be a clear policy decision and I could move on).  And whatever you choose, do it consistently from the next version onwards and across different functions, document those things and test for them.

**Comment by jay-jlm** [comment] 2018-02-26 22:00
But wait, this specific issue is not related to the functionality or the implementation of the function.
It's just about how the current description of the return types in the documentation is at odds with with the function's actual return types.
I know that for advanced users they usually rely on the function signature at the top but for newcomers like me the English text is what we usually check first and right now it's misleading

**Comment by CrossEye** [comment] 2018-02-27 02:19
@jay-jlm: We often document *aspirationally*, describing how we expect the function to be used, and not trying to cover every corner case.  I'm suggesting that in this case, we might be better off changing the functionality than the documentation.  To anyone using this as it's been documented, there would be no change.

I am very much mixed about this.  I don't care much about `and` here, but I have used `or` in the way that it's written, essentially an prefix version of the Javascript `||` operator, taking advantage of the features of `||`.  But this keeps coming up, and I think we need to do something.

**Comment by CrossEye** [comment] 2018-02-27 02:25
@polytypic: 

While you make many good points, what do you think the right balance is?  Ok, we should make a stance and stick with it.  But what stance?

I'm not interested in run-time type-checking every parameter.  If users want that style, there's already Sanctuary.  Could we improve simply by adding nil-checking everywhere it might matter?   How big an effort would that be?  And would it be enough?  Even if we do, when do we throw?  My go-to example is often `propOr`: there's a reasonable output even if the object parameter is `null`; the user has already said what she wants if that property doesn't exist.  I would have a hard time throwing here.  But that already makes me feel as though we'd likely become *ad hoc* in our choices.

I'd love to hear a more detailed proposal for how to fix this.

**Comment by semmel** [comment] 2018-02-27 18:47
>I'm not interested in run-time type-checking every parameter.  

Given this assumption, I see no solution.

>Could we improve simply by adding nil-checking everywhere it might matter?

I don't think so. Is calling a Ramda function with a *nil* in any way worse than with a value of the *wrong type*, so we may let the latter happen without any reaction?

I'd guess these examples may break on any Ramda release in the future:
```javascript
R.head({key: "value", 0: "first"}); // -> 'first'
R.has(1)([10, 0]); // -> true
R.prop(1, "abc"); // -> 'b'
``` 

As @polytypic says, it's sometimes desired (e.g. when treating a `String` as a `List` type Ramda makes a nice string utility library too) and mostly not (better use a dedicated string utility - really). And I agree that these "unorthodox usages" create undesirable time bombs.

`R.propOr` is indeed a very good example: Depending on what assumptions I make for provided *data* (which is supposed to be an Object)  `R.propOr("default", "impossible", data) === 'default' ` while `data == 9` maybe surprising or not.

I certainly cannot predict the behaviour from the function name `propOr`: Is the logical `or` bound to the data or the property? A nice thing is that for the current implementation that *does not matter* as long as one is OK with `R.prop("impossible", 9) === undefined`. So in a very JavaScript-kind of way `data` can have any type.

The problem is that the documentation raises false expectations for `R.propOr` in providing a type signature of `a → String → Object → a` instead of `a → String → * → a`.

**Comment by CrossEye** [comment] 2018-02-27 22:19
> The problem is that the documentation raises false expectations for `R.propOr` in providing a type signature of `a → String → Object → a` instead of `a → String → * → a`.

I'm not sure what that false expectation is.  These signatures were adapted from Haskell.  But in Haskell, you simply cannot compile `propOr "default" "impossible" 9`.  You never run into any expectation; or, better, you expect this to fail at compile time.  Ramda, sitting atop Javascript, cannot control that.  Do you expect an exception?  If so, of what type?  Do you expect the program to crash?  Or do you expect that Ramda will try to respond?  That last is what it currently does, and since the user has already answered the question of what she would like in the case that the supplied data does not have the requested property, we can happily answer respond with the default.

But note that if the user does supply the types mentioned in the signature, this function should work as described.  If that's not the case, then we have larger issues.

>> I'm not interested in run-time type-checking every parameter.

> Given this assumption, I see no solution.

I don't know if you think this is a really bad thing.

Do you see a place for Ramda alongside Sanctuary?  Sanctuary accepts Ramda's main ideas of bringing FP ideas into Javascript with pure functions on immutable data and with some notion of working with arbitrary types.  Sanctuary extends these ideas with run-time type-checking and more total functions and removes any variadic support.  (It does this in some sense at the cost of performance, but that's never been a major factor for either library.)

Does having both libraries available make sense to you, or do you think that Ramda should either go away or follow Sanctuary's path?

**Comment by semmel** [comment] 2018-02-28 01:16
>These signatures were adapted from Haskell

Okay I don't know Haskell and thus I interpret the signatures more like they were TypeScript annotations, C++ type declarations or Php type-hints. Maybe I shouldn't.

>...in the case that the supplied data does not have the requested property we can happily answer respond with the default.

I guess I have a problem of thinking that a primitive like 9 can have a property because it is not an object. Thus in my understanding from the documentation I am using R.propOr wrong.

>>>I'm not interested in run-time type-checking every parameter.

>>Given this assumption, I see no solution.

I mean that in a naive way: If the problem is reacting to invalid inputs there need to be runtime checks, don't they? 
Not checking every input type but *some* on nil makes no sense for me. Either all or nothing. What's so special about null and undefined? Are not "", {} and [] the *empty* / fallback containers? Keeping a null or undefined for more than a few lines in my code I consider a bug. Even in sparse arrays it does not matter if the iteration skips over these gaps.

**Comment by CrossEye** [comment] 2018-02-28 05:19
@semmel: First off, I want to apologize.  I just reread my previous comment and it sounds very argumentative.  It was not at all meant that way.  I really want to hear possible solutions to what is a very significant dilemma in Ramda.  Sorry about that.

>> These signatures were adapted from Haskell

> Okay I don't know Haskell and thus I interpret the signatures more like they were TypeScript annotations, C++ type declarations or Php type-hints. Maybe I shouldn't.

They overlap a fair bit with C++ declarations, and to some extent with TypeScript annotations.  My PHP was a long ago, and I don't think type-hints existed there then, so I don't know.  These signatures are widely accepted in the FP world.  Even in those languages where they are not used internally, there is a large community of people who will understand them.

The point I was making, though, is that these are designed for languages that are much more strongly typed than Javascript -- much more too than TypeScript, Java, C#, *et. al.*.  They are useful documentation in languages like Haskell, although often they are unnecessary, as they can be derived.  But they are not mere documentation; they are enforced by the compiler.

In Javascript, we do not have that luxury.  In a loosely-typed language, whatever compilation we have cannot check that values are of the correct type.  So I think of the type signatures in Ramda as contracts: *if you supply* this *then we will return* that.  But we don't necessarily specify what happens if you don't supply the correct types.  If you void the warranty, all bets are off.

Sanctuary has a very different solution: it does the best it can to check types at runtime.  Ramda will happily do this:

```js
const oddString = x => x % 2 === 0 ? x : '' + x
R.map(oddString, [1, 2, 3]) //=> ['1', 2, '3']
```

whereas Sanctuary will give you a wonderfully detailed error message about numbers and strings sharing no common type.

Ramda is less opinionated.  You can say this is a library for grown-ups; we expect you know what you're doing.  Or you can say it is an unsafe library.  They are two sides of the same coin.  (TypeScript, with its compilation step, offers another option.  I could supply my `Index = String | Number` type and not generate any errors.  It might be that Sanctuary has this too; I'm not as versed in it as I was during Sanctuary's early days.)



>>    ...in the case that the supplied data does not have the requested property we can happily answer respond with the default.

> I guess I have a problem of thinking that a primitive like 9 can have a property because it is not an object. Thus in my understanding from the documentation I am using R.propOr wrong.

Yes, you are using it wrong if you supply `9`, or `null`, or `false`.  How we should handle it is what's under question. @buzzdecafe and I have slightly different philosophies.  His is more straightforward: *let it fail*.  This might take the shape of allowing whatever happens to fall out of the implementation, or, less commonly, we might do some specific checking on types and intentionally throw an exception.  But we do no hand-holding whatsoever.  Mine is slightly more nuanced: I think that for some functions, we have enough information, even in the case of bad types, to still properly return an appropriate value.  In those cases, we should do so.  Otherwise, again, *let it fail*.

The point in either case is that if you supply items of the correct type, you will get a response of the correct type.  So the signatures are right.  If you supply the wrong types, don't count on anything.



>>>> I'm not interested in run-time type-checking every parameter.

>>>Given this assumption, I see no solution.

> I mean that in a naive way: 

I also mean mine naively.  **I** am not interested in this.  I don't want to write it or maintain it.  I'd rather it doesn't clutter up my clean code.  But that doesn't preclude my checking them occasionally, where it makes sense.  Again, `propOr` is useful, because it already encompasses, precisely in its definition, what should happen when the data object does not match expectations.


> If the problem is reacting to invalid inputs there need to be runtime checks, don't they

Not precisely checks, but something similar.  I've written plenty of JS code over my career that works like this:

```js
(foo() || []).concat('bar')
```

This doesn't check that `foo` returns an array, but in the case it returns `undefined` or `null`, the code continues to function.

> Not checking every input type but some on nil makes no sense for me. Either all or nothing. 

Which would be better in your opinion?  "all" or "nothing"?

> What's so special about null and undefined?

 Nothing intrinsic, but they are such common results from other steps you might use, that handling them appropriately can sometimes seem like a good idea.

----------

I hope you recognize, then, that this is not something that's slipped through the cracks.  It's been debated on and off since the early days of Ramda's predecessor.  We haven't gotten it right, not entirely.  And trying to figure it out consumes a fair bit of our attention.

**Comment by semmel** [comment] 2018-02-28 15:05
@CrossEye No need to apologize! On the contrary I am very grateful that you patiently give so much valuable advice here.

Sorry for the bloat, but let me first repeat some of your and then @polytypic statements which make now more sense to me (*emphasis* mine):
> So I think of the type signatures in Ramda as contracts: if you supply this then we will return that. But we don't necessarily specify what happens if you don't supply the correct types.
...
@buzzdecafe 's ..philosophy is more straightforward: let it fail .. whatever happens to fall out of the implementation. ... I think that for some functions, we have enough information, even in the case of bad types, to still properly return an appropriate value. In those cases, we should do so. Otherwise, again, let it fail.

>Ramda seems to be designed with only the "happy path" in mind, but in real projects I need to write code that does something consistent even in unfortunate and more challenging scenarios.
...
It is very easy to accidentally write code that makes such assumptions (based on the *current observed behaviour*). This basically sets up a time bomb. ...  On the other hand, not being able to rely on anything but the happy path behaviour means that many use cases have to add extra defensive code around uses of R.prop to behave consistently. Neither of these is OK, IMHO.

So there are
- the type signature and documentation for the "happy path",
- in some cases an intentionally hand-holding implementation which will return an "appropriate value", and
- the "current observed behaviour" (current implementation), which given an odd set of inputs may calculate the cure for cancer or may create a black hole which swallows the earth.

Shouldn't the documentation (i.e. type signature) at least reflect any *intentionally* hand-holding in the implementation? E.g. for `R.propOr` it should finally be `a → String → * → a` then? (Sorry I don't mean to be stubborn - but maybe I am.)

IMO if it's not documented and may change any release, implementing the slightest hand-holding is in vain and I'd go with @buzzdecafe's way of "Let it fail". (Which unfortunately will put the burden on the user code)

To tolerate `nil` inputs could one not mechanically default to `""`, `{}` and `[]` like you suggested?
```javascript
(listParameter || []).concat([8]);
(stringParameter || "").concat('bar')
```

**Comment by polytypic** [comment] 2018-02-28 15:33
Apologies in advance, I should take a bit more time to read the backlog, but about:

> let it fail

That would be OK if indeed Ramda would fail consistently.  But that is not the case.  Sometimes things appear to work by accident, like the `R.omit` case I mentioned earlier, and that is not OK IMHO.

**Comment by CrossEye** [comment] 2018-02-28 16:19
> - the "current observed behaviour" (current implementation), which given an odd set of inputs may calculate the cure for cancer or may create a black hole which swallows the earth.

:smile: Don't forget bringing about world peace and stealing your girlfriend.

>Shouldn't the documentation (i.e. type signature) at least reflect any intentionally hand-holding in the implementation? E.g. for `R.propOr` it should finally be `a → String → * → a` then?

I think we certainly could in those cases where we actually handle arbitrary types like this one.  I would prefer `a → String → b → a`, but it's the same idea.  (I'd like to get rid of all asterisks in our signatures, if we can.)

> To tolerate `nil` inputs could one not mechanically default to `""`, `{}` and `[]` like you suggested?

Yes, if we're only concerned with `nil` input and not with entirely wrong types.  I don't know how much help this would offer, and it would still run afoul of the stated preference of @buzzdecafe.  But yes, this is possible, at least sometimes.  It's not a universal solution, though.  For instance, using the empty string in place of the `name` parameter in `prop` could lead to some unusual behavior:

 ```js
prop(undefined, {a: 1, b: 2}) //=> undefined,  as expected, but
prop(undefined, {a: 1, b: 2, '': 42) //=> 42: ???
```
and possibilities like this scare me.

But the elephant in the room are the functions, and here I don't think it's reasonable to replace missing function with the only candidate, `identity`.  I'm having a harder time coming up with a simple example, which may mean this is less of an issue than I thought.  But I *can* come up with one, so there's something here.  If we changed `map` to default to the identity function, we'd get behavior like this:

```js
const fns = {
  vowels: compose(length, filter(contains(__, ['a', 'e', 'i', 'o', 'u'])), split('')),
  consonants: compose(length, reject(contains(__, ['a', 'e', 'i', 'o', 'u'])), split('')),
  letters: length,
}

// details :: String -> [String] -> [Int]
const details = curry((type, strs) => map(fns[type], strs));

details('vowels', ['strengths', 'aerie', 'banana']) // [1, 4, 3]
details('consonants', ['strengths', 'aerie', 'banana']) // => [8, 1, 3]
details('letters', ['strengths', 'aerie', 'banana']) // => [9, 5, 6]
details('consonents', ['strengths', 'aerie', 'banana']) // => ["strengths", "aerie", "banana"] 
//             ^-- typo 
```

That last one returns the wrong type, because `map` didn't do the expected transform.  Here I'm much more inclined to agree with @buzzdecafe's "let it fail".  There seems no better option.

**Comment by semmel** [comment] 2018-02-28 17:52
>I don't think it's reasonable to replace missing function with the only candidate, `identity`

Yes, it would produce some funny unhelpful results when mapping with `identity` over a collection instead of e.g. `R.prop`. Also when `identity` is used as a default for predicate functions in like `R.any, R.all, R.propSatisfies`, the parameter bug will appear later.  But isn't that the principle of "Let it fail .. with whatever the implementation comes up" to the extreme? 

It would be a bit like the horror errors the C++ compiler produces when you feed a template the wrong type. (Besides: C++20 will get "concepts" which is like another flexible type system in a way?)

While throwing an error from Ramda is in those cases certainly better to find bugs in the development phase, for that purpose I also have unit tests and dictionary-powered assistive typing in the IDE. (The latter would have detected the typo in your example :smile: )

**Comment by customcommander** [comment] 2022-04-03 20:07
Closing for now as #3170 has clarified the documentation.

**Closed by customcommander** 2022-04-03 20:07 UTC
Labels: documentation
