### ISSUE TITLE
Bad edits in cookbook?

### ISSUE THREAD

**Issue by robations** [ramda/ramda#2657] opened 2018-09-21 15:18 UTC
At least the last edit by @GingerPlusPlus seems to have left the cookbook in an inconsistent state. The last 10 or so edits have no description so it's hard to understand what was intended.

For example, the `objSize` definition is deleted, but the list of examples is still there.

Perhaps someone more familiar with this can take a look. I don't want to wade in and revert a bunch of edits which maybe were good/bad.

**Comment by GingerPlusPlus** [comment] 2018-09-21 16:12
> the `objSize` definition is deleted, but the list of examples is still there.

I removed `objSize`, it was overcomplicated duplicate of `size`.

I didn't update table of contents because of the comment at the begging of it:

```
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
```

From what I see, to update TOC you need to clone the wiki (`git clone https://github.com/ramda/ramda.wiki.git`) and run `update-cookbook-toc.sh`.

**Comment by CrossEye** [comment] 2018-09-22 21:06
I think that's right.  It's been a long time since I've done this.

**Comment by robations** [comment] 2018-09-24 11:05
@GingerPlusPlus agree with you about `objSize` being overcomplicated, just there is a bunch of examples for `objSize` left in the doc at the moment:

```
objSize(); // 0
objSize(undefined); // 0
objSize(null); // 0
...
```

**Closed** 2019-12-22 15:23 UTC
