### ISSUE TITLE
documentation: indentation not preserved

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda#756] opened 2015-01-25 23:31 UTC
[Input](https://github.com/ramda/ramda/blob/v0.9.0/src/call.js):

```javascript
var indentN = R.pipe(R.times(R.always(' ')),
                     R.join(''),
                     R.replace(/^(?!$)/gm));

var format = R.converge(R.call,
                        R.pipe(R.prop('indent'), indentN),
                        R.prop('value'));

format({indent: 2, value: 'foo\nbar\nbaz\n'}); //=> '  foo\n  bar\n  baz\n'
```

[Output](http://ramdajs.com/docs/#call):

```javascript
var indentN = R.pipe(R.times(R.always(' ')),
R.join(''),
R.replace(/^(?!$)/gm));

var format = R.converge(R.call,
R.pipe(R.prop('indent'), indentN),
R.prop('value'));

format({indent: 2, value: 'foo\nbar\nbaz\n'}); //=> '  foo\n  bar\n  baz\n'
```

**Comment by buzzdecafe** [comment] 2015-01-26 13:51
duplicate of #715

**Closed** 2015-01-26 14:34 UTC
Labels: documentation, duplicate
